from typing import List, Dict, Any, Optional
import httpx
import logging
from backend.app.services.injury_registry import get_injury_details, HEALTHY_STARTERS, normalize_name

logger = logging.getLogger(__name__)

# Calibrated NFL Fantasy Database (Current Consensus for 10-Team Full-PPR)
INITIAL_PLAYERS: List[Dict[str, Any]] = [
    {'id': 'wr-chase', 'name': "Ja'Marr Chase", 'position': 'WR', 'team': 'CIN', 'adp': 1.2, 'tier': 1, 'projected_season': 355.0, 'projected_week': 22.2, 'xfp': 21.8, 'route_participation': 0.95, 'high_value_touches': 6.8, 'red_zone_share': 0.38, 'target_share': 0.3, 'proe': 0.08, 'espn_ownership': 100.0, 'espn_proj': 21.5, 'bye_week': 12, 'opponent': 'PIT', 'implied_team_pts': 26.5, 'spread': -3.5, 'wind_mph': 6, 'is_dome': False, 'opp_rank_vs_pos': 18, 'archetype': 'Consensus 1.01 Alpha Target Monster'},
    {'id': 'wr-jj', 'name': 'Justin Jefferson', 'position': 'WR', 'team': 'MIN', 'adp': 2.5, 'tier': 1, 'projected_season': 345.0, 'projected_week': 21.5, 'xfp': 20.8, 'route_participation': 0.96, 'high_value_touches': 6.2, 'red_zone_share': 0.35, 'target_share': 0.29, 'proe': 0.05, 'espn_ownership': 100.0, 'espn_proj': 20.8, 'bye_week': 6, 'opponent': 'CHI', 'implied_team_pts': 24.5, 'spread': -2.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 16, 'archetype': 'Elite Route Technician / QB-Proof'},
    {'id': 'rb-bijan', 'name': 'Bijan Robinson', 'position': 'RB', 'team': 'ATL', 'adp': 3.2, 'tier': 1, 'projected_season': 335.0, 'projected_week': 20.9, 'xfp': 20.4, 'route_participation': 0.74, 'high_value_touches': 6.8, 'red_zone_share': 0.46, 'target_share': 0.18, 'proe': 0.02, 'espn_ownership': 100.0, 'espn_proj': 20.1, 'bye_week': 12, 'opponent': 'CAR', 'implied_team_pts': 25.5, 'spread': -4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 30, 'archetype': 'Consensus RB1 / Full-PPR Bellcow (Zero QB Vulture)'},
    {'id': 'wr-ceedee', 'name': 'CeeDee Lamb', 'position': 'WR', 'team': 'DAL', 'adp': 4.5, 'tier': 1, 'projected_season': 330.0, 'projected_week': 20.6, 'xfp': 20.1, 'route_participation': 0.94, 'high_value_touches': 6.0, 'red_zone_share': 0.35, 'target_share': 0.29, 'proe': 0.07, 'espn_ownership': 100.0, 'espn_proj': 20.0, 'bye_week': 7, 'opponent': 'NYG', 'implied_team_pts': 26.5, 'spread': -6.5, 'wind_mph': 5, 'is_dome': True, 'opp_rank_vs_pos': 26, 'archetype': 'High-Volume Slot/Wide Target Hog'},
    {'id': 'wr-amonra', 'name': 'Amon-Ra St. Brown', 'position': 'WR', 'team': 'DET', 'adp': 5.8, 'tier': 1, 'projected_season': 322.0, 'projected_week': 20.1, 'xfp': 19.6, 'route_participation': 0.95, 'high_value_touches': 5.6, 'red_zone_share': 0.33, 'target_share': 0.28, 'proe': 0.01, 'espn_ownership': 100.0, 'espn_proj': 19.5, 'bye_week': 5, 'opponent': 'GB', 'implied_team_pts': 27.5, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 22, 'archetype': 'PPR Bank Vault Floor & Ceiling'},
    {'id': 'rb-gibbs', 'name': 'Jahmyr Gibbs', 'position': 'RB', 'team': 'DET', 'adp': 6.5, 'tier': 1, 'projected_season': 318.0, 'projected_week': 19.9, 'xfp': 19.2, 'route_participation': 0.68, 'high_value_touches': 6.2, 'red_zone_share': 0.4, 'target_share': 0.17, 'proe': 0.01, 'espn_ownership': 100.0, 'espn_proj': 19.2, 'bye_week': 5, 'opponent': 'GB', 'implied_team_pts': 27.5, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 20, 'archetype': 'Consensus RB2 / Elite PPR Target & Explosive Monster'},
    {'id': 'rb-breece', 'name': 'Breece Hall', 'position': 'RB', 'team': 'NYJ', 'adp': 7.8, 'tier': 1, 'projected_season': 305.0, 'projected_week': 19.0, 'xfp': 18.4, 'route_participation': 0.65, 'high_value_touches': 5.6, 'red_zone_share': 0.38, 'target_share': 0.18, 'proe': -0.01, 'espn_ownership': 99.8, 'espn_proj': 18.5, 'bye_week': 12, 'opponent': 'NE', 'implied_team_pts': 23.0, 'spread': -5.5, 'wind_mph': 11, 'is_dome': False, 'opp_rank_vs_pos': 21, 'archetype': 'Dual-Threat Workhorse / High Target Share'},
    {'id': 'rb-saquon', 'name': 'Saquon Barkley', 'position': 'RB', 'team': 'PHI', 'adp': 8.8, 'tier': 1, 'projected_season': 292.0, 'projected_week': 18.2, 'xfp': 17.6, 'route_participation': 0.6, 'high_value_touches': 5.0, 'red_zone_share': 0.34, 'target_share': 0.12, 'proe': -0.04, 'espn_ownership': 100.0, 'espn_proj': 18.5, 'bye_week': 5, 'opponent': 'WAS', 'implied_team_pts': 28.5, 'spread': -8.0, 'wind_mph': 7, 'is_dome': False, 'opp_rank_vs_pos': 28, 'archetype': 'Elite Rusher (Penalized for Hurts Tush Push & 12% Target Share)'},
    {'id': 'wr-nabers', 'name': 'Malik Nabers', 'position': 'WR', 'team': 'NYG', 'adp': 9.5, 'tier': 1, 'projected_season': 300.0, 'projected_week': 18.8, 'xfp': 19.1, 'route_participation': 0.96, 'high_value_touches': 5.8, 'red_zone_share': 0.38, 'target_share': 0.32, 'proe': 0.04, 'espn_ownership': 99.8, 'espn_proj': 17.9, 'bye_week': 11, 'opponent': 'DAL', 'implied_team_pts': 21.0, 'spread': 6.5, 'wind_mph': 5, 'is_dome': True, 'opp_rank_vs_pos': 14, 'archetype': 'Generational Target Magnet'},
    {'id': 'wr-nico', 'name': 'Nico Collins', 'position': 'WR', 'team': 'HOU', 'adp': 10.5, 'tier': 1, 'projected_season': 295.0, 'projected_week': 18.4, 'xfp': 18.3, 'route_participation': 0.91, 'high_value_touches': 5.2, 'red_zone_share': 0.33, 'target_share': 0.28, 'proe': 0.06, 'espn_ownership': 99.6, 'espn_proj': 18.0, 'bye_week': 14, 'opponent': 'IND', 'implied_team_pts': 26.0, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 24, 'archetype': 'Stroud Alpha Deep/YAC Dominator'},
    {'id': 'rb-henry', 'name': 'Derrick Henry', 'position': 'RB', 'team': 'BAL', 'adp': 11.5, 'tier': 2, 'projected_season': 288.0, 'projected_week': 18.0, 'xfp': 17.5, 'route_participation': 0.36, 'high_value_touches': 4.8, 'red_zone_share': 0.52, 'target_share': 0.07, 'proe': -0.06, 'espn_ownership': 99.9, 'espn_proj': 17.8, 'bye_week': 14, 'opponent': 'CLE', 'implied_team_pts': 27.5, 'spread': -6.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 12, 'archetype': 'Unstoppable Goal-Line Touchdown Machine'},
    {'id': 'rb-cmc', 'name': 'Christian McCaffrey', 'position': 'RB', 'team': 'SF', 'adp': 12.5, 'tier': 2, 'projected_season': 285.0, 'projected_week': 17.8, 'xfp': 17.6, 'route_participation': 0.65, 'high_value_touches': 5.0, 'red_zone_share': 0.36, 'target_share': 0.15, 'proe': 0.03, 'espn_ownership': 99.7, 'espn_proj': 17.5, 'bye_week': 9, 'opponent': 'LAR', 'implied_team_pts': 26.0, 'spread': -4.0, 'wind_mph': 4, 'is_dome': False, 'opp_rank_vs_pos': 24, 'archetype': 'Elite PPR Weapon (Calf Tightness Monitored)'},
    {'id': 'wr-btj', 'name': 'Brian Thomas Jr.', 'position': 'WR', 'team': 'JAX', 'adp': 14.0, 'tier': 2, 'projected_season': 280.0, 'projected_week': 17.5, 'xfp': 17.2, 'route_participation': 0.93, 'high_value_touches': 4.8, 'red_zone_share': 0.31, 'target_share': 0.27, 'proe': 0.03, 'espn_ownership': 99.2, 'espn_proj': 16.9, 'bye_week': 12, 'opponent': 'TEN', 'implied_team_pts': 23.5, 'spread': -2.5, 'wind_mph': 7, 'is_dome': False, 'opp_rank_vs_pos': 27, 'archetype': 'Electrifying Breakout Deep Threat Alpha'},
    {'id': 'wr-marv', 'name': 'Marvin Harrison Jr.', 'position': 'WR', 'team': 'ARI', 'adp': 15.5, 'tier': 2, 'projected_season': 275.0, 'projected_week': 17.2, 'xfp': 16.8, 'route_participation': 0.92, 'high_value_touches': 4.6, 'red_zone_share': 0.32, 'target_share': 0.26, 'proe': 0.02, 'espn_ownership': 99.0, 'espn_proj': 16.8, 'bye_week': 11, 'opponent': 'SEA', 'implied_team_pts': 23.0, 'spread': 1.5, 'wind_mph': 6, 'is_dome': False, 'opp_rank_vs_pos': 19, 'archetype': 'Year 2 Leap Alpha'},
    {'id': 'wr-ajbrown', 'name': 'A.J. Brown', 'position': 'WR', 'team': 'NE', 'adp': 16.5, 'tier': 2, 'projected_season': 270.0, 'projected_week': 16.9, 'xfp': 16.5, 'route_participation': 0.91, 'high_value_touches': 4.5, 'red_zone_share': 0.28, 'target_share': 0.25, 'proe': -0.04, 'espn_ownership': 99.5, 'espn_proj': 16.9, 'bye_week': 5, 'opponent': 'WAS', 'implied_team_pts': 28.5, 'spread': -8.0, 'wind_mph': 7, 'is_dome': False, 'opp_rank_vs_pos': 29, 'archetype': 'Physical YAC Alpha'},
    {'id': 'rb-jt', 'name': 'Jonathan Taylor', 'position': 'RB', 'team': 'IND', 'adp': 17.5, 'tier': 2, 'projected_season': 268.0, 'projected_week': 16.8, 'xfp': 16.2, 'route_participation': 0.54, 'high_value_touches': 4.6, 'red_zone_share': 0.42, 'target_share': 0.1, 'proe': -0.05, 'espn_ownership': 99.4, 'espn_proj': 16.5, 'bye_week': 14, 'opponent': 'HOU', 'implied_team_pts': 22.5, 'spread': 3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 17, 'archetype': 'Pure Volume Rusher'},
    {'id': 'te-bowers', 'name': 'Brock Bowers', 'position': 'TE', 'team': 'LV', 'adp': 18.5, 'tier': 1, 'projected_season': 265.0, 'projected_week': 16.5, 'xfp': 16.2, 'route_participation': 0.9, 'high_value_touches': 4.8, 'red_zone_share': 0.3, 'target_share': 0.26, 'proe': 0.01, 'espn_ownership': 99.5, 'espn_proj': 15.5, 'bye_week': 10, 'opponent': 'DEN', 'implied_team_pts': 21.0, 'spread': 2.5, 'wind_mph': 6, 'is_dome': True, 'opp_rank_vs_pos': 28, 'archetype': 'Historic TE1 Positional Cheat Code'},
    {'id': 'wr-tyreek', 'name': 'Tyreek Hill', 'position': 'WR', 'team': 'MIA', 'adp': 19.5, 'tier': 2, 'projected_season': 260.0, 'projected_week': 16.2, 'xfp': 15.8, 'route_participation': 0.88, 'high_value_touches': 4.2, 'red_zone_share': 0.25, 'target_share': 0.25, 'proe': 0.05, 'espn_ownership': 99.6, 'espn_proj': 16.8, 'bye_week': 6, 'opponent': 'BUF', 'implied_team_pts': 24.0, 'spread': 2.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 15, 'archetype': 'High-Variance Speed Veteran'},
    {'id': 'wr-puka', 'name': 'Puka Nacua', 'position': 'WR', 'team': 'LAR', 'adp': 20.5, 'tier': 2, 'projected_season': 258.0, 'projected_week': 16.1, 'xfp': 16.0, 'route_participation': 0.9, 'high_value_touches': 4.6, 'red_zone_share': 0.28, 'target_share': 0.27, 'proe': 0.03, 'espn_ownership': 99.1, 'espn_proj': 16.2, 'bye_week': 6, 'opponent': 'SF', 'implied_team_pts': 22.0, 'spread': 4.0, 'wind_mph': 4, 'is_dome': False, 'opp_rank_vs_pos': 16, 'archetype': 'PPR Target Sponge'},
    {'id': 'rb-jacobs', 'name': 'Josh Jacobs', 'position': 'RB', 'team': 'GB', 'adp': 21.5, 'tier': 2, 'projected_season': 255.0, 'projected_week': 15.9, 'xfp': 15.5, 'route_participation': 0.52, 'high_value_touches': 4.5, 'red_zone_share': 0.45, 'target_share': 0.1, 'proe': -0.01, 'espn_ownership': 98.8, 'espn_proj': 15.8, 'bye_week': 10, 'opponent': 'DET', 'implied_team_pts': 24.5, 'spread': 3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 17, 'archetype': 'High-Value TD Workhorse'},
    {'id': 'rb-kyren', 'name': 'Kyren Williams', 'position': 'RB', 'team': 'LAR', 'adp': 22.5, 'tier': 2, 'projected_season': 250.0, 'projected_week': 15.6, 'xfp': 15.4, 'route_participation': 0.6, 'high_value_touches': 4.6, 'red_zone_share': 0.44, 'target_share': 0.11, 'proe': 0.02, 'espn_ownership': 98.7, 'espn_proj': 15.5, 'bye_week': 6, 'opponent': 'SF', 'implied_team_pts': 22.0, 'spread': 4.0, 'wind_mph': 4, 'is_dome': False, 'opp_rank_vs_pos': 16, 'archetype': 'Red Zone Conversion Specialist'},
    {'id': 'rb-achane', 'name': "De'Von Achane", 'position': 'RB', 'team': 'MIA', 'adp': 23.5, 'tier': 3, 'projected_season': 248.0, 'projected_week': 15.5, 'xfp': 14.5, 'route_participation': 0.62, 'high_value_touches': 4.4, 'red_zone_share': 0.3, 'target_share': 0.16, 'proe': 0.05, 'espn_ownership': 98.6, 'espn_proj': 15.2, 'bye_week': 6, 'opponent': 'BUF', 'implied_team_pts': 24.0, 'spread': 2.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 20, 'archetype': 'Nuclear Ceiling / Home Run Hitter'},
    {'id': 'qb-lamar', 'name': 'Lamar Jackson', 'position': 'QB', 'team': 'BAL', 'adp': 25.0, 'tier': 1, 'projected_season': 380.0, 'projected_week': 23.8, 'xfp': 23.5, 'route_participation': 0.0, 'high_value_touches': 5.2, 'red_zone_share': 0.35, 'target_share': 0.0, 'proe': -0.05, 'espn_ownership': 100.0, 'espn_proj': 23.5, 'bye_week': 14, 'opponent': 'CLE', 'implied_team_pts': 27.5, 'spread': -6.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 12, 'archetype': '2x MVP Konami Code Ceiling'},
    {'id': 'qb-allen', 'name': 'Josh Allen', 'position': 'QB', 'team': 'BUF', 'adp': 26.5, 'tier': 1, 'projected_season': 375.0, 'projected_week': 23.4, 'xfp': 23.0, 'route_participation': 0.0, 'high_value_touches': 4.8, 'red_zone_share': 0.36, 'target_share': 0.0, 'proe': 0.03, 'espn_ownership': 100.0, 'espn_proj': 23.2, 'bye_week': 12, 'opponent': 'MIA', 'implied_team_pts': 26.5, 'spread': -2.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 20, 'archetype': 'Dual-Threat Touchdown Machine'},
    {'id': 'qb-daniels', 'name': 'Jayden Daniels', 'position': 'QB', 'team': 'WAS', 'adp': 27.5, 'tier': 1, 'projected_season': 365.0, 'projected_week': 22.8, 'xfp': 22.5, 'route_participation': 0.0, 'high_value_touches': 5.0, 'red_zone_share': 0.34, 'target_share': 0.0, 'proe': 0.04, 'espn_ownership': 99.8, 'espn_proj': 22.0, 'bye_week': 14, 'opponent': 'PHI', 'implied_team_pts': 23.5, 'spread': 8.0, 'wind_mph': 7, 'is_dome': False, 'opp_rank_vs_pos': 25, 'archetype': 'Elite Rushing QB Superstar'},
    {'id': 'qb-hurts', 'name': 'Jalen Hurts', 'position': 'QB', 'team': 'PHI', 'adp': 29.0, 'tier': 1, 'projected_season': 355.0, 'projected_week': 22.2, 'xfp': 21.8, 'route_participation': 0.0, 'high_value_touches': 4.6, 'red_zone_share': 0.4, 'target_share': 0.0, 'proe': -0.04, 'espn_ownership': 99.7, 'espn_proj': 21.8, 'bye_week': 5, 'opponent': 'WAS', 'implied_team_pts': 28.5, 'spread': -8.0, 'wind_mph': 7, 'is_dome': False, 'opp_rank_vs_pos': 29, 'archetype': 'Tush Push Rushing Floor Anchor'},
    {'id': 'te-mcbride', 'name': 'Trey McBride', 'position': 'TE', 'team': 'ARI', 'adp': 30.0, 'tier': 1, 'projected_season': 235.0, 'projected_week': 14.7, 'xfp': 14.8, 'route_participation': 0.9, 'high_value_touches': 3.8, 'red_zone_share': 0.26, 'target_share': 0.25, 'proe': 0.02, 'espn_ownership': 98.8, 'espn_proj': 14.2, 'bye_week': 11, 'opponent': 'SEA', 'implied_team_pts': 23.0, 'spread': 1.5, 'wind_mph': 6, 'is_dome': False, 'opp_rank_vs_pos': 25, 'archetype': 'High-Volume Target Sponge TE'},
    {'id': 'te-kittle', 'name': 'George Kittle', 'position': 'TE', 'team': 'SF', 'adp': 31.5, 'tier': 1, 'projected_season': 225.0, 'projected_week': 14.1, 'xfp': 13.9, 'route_participation': 0.86, 'high_value_touches': 3.5, 'red_zone_share': 0.28, 'target_share': 0.22, 'proe': 0.03, 'espn_ownership': 98.5, 'espn_proj': 13.8, 'bye_week': 9, 'opponent': 'LAR', 'implied_team_pts': 26.0, 'spread': -4.0, 'wind_mph': 4, 'is_dome': False, 'opp_rank_vs_pos': 23, 'archetype': 'Elite YAC & Red Zone Dominator'},
    {'id': 'wr-london', 'name': 'Drake London', 'position': 'WR', 'team': 'ATL', 'adp': 33.0, 'tier': 3, 'projected_season': 248.0, 'projected_week': 15.5, 'xfp': 15.4, 'route_participation': 0.94, 'high_value_touches': 4.4, 'red_zone_share': 0.32, 'target_share': 0.27, 'proe': 0.02, 'espn_ownership': 98.2, 'espn_proj': 15.0, 'bye_week': 12, 'opponent': 'CAR', 'implied_team_pts': 25.5, 'spread': -4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 27, 'archetype': 'Contested Catch Alpha WR1'},
    {'id': 'wr-gw', 'name': 'Garrett Wilson', 'position': 'WR', 'team': 'NYJ', 'adp': 34.5, 'tier': 3, 'projected_season': 245.0, 'projected_week': 15.3, 'xfp': 15.2, 'route_participation': 0.95, 'high_value_touches': 4.2, 'red_zone_share': 0.26, 'target_share': 0.27, 'proe': -0.01, 'espn_ownership': 98.0, 'espn_proj': 15.0, 'bye_week': 12, 'opponent': 'NE', 'implied_team_pts': 23.0, 'spread': -5.5, 'wind_mph': 11, 'is_dome': False, 'opp_rank_vs_pos': 16, 'archetype': 'PPR Route Running Funnel'},
    {'id': 'rb-cook', 'name': 'James Cook', 'position': 'RB', 'team': 'BUF', 'adp': 36.0, 'tier': 3, 'projected_season': 235.0, 'projected_week': 14.7, 'xfp': 14.2, 'route_participation': 0.58, 'high_value_touches': 4.0, 'red_zone_share': 0.35, 'target_share': 0.12, 'proe': 0.03, 'espn_ownership': 97.5, 'espn_proj': 14.4, 'bye_week': 12, 'opponent': 'MIA', 'implied_team_pts': 26.5, 'spread': -2.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 20, 'archetype': 'Dynamic Ground & Air Weapon'},
    {'id': 'rb-bucky', 'name': 'Bucky Irving', 'position': 'RB', 'team': 'TB', 'adp': 38.0, 'tier': 3, 'projected_season': 230.0, 'projected_week': 14.4, 'xfp': 14.5, 'route_participation': 0.56, 'high_value_touches': 4.3, 'red_zone_share': 0.38, 'target_share': 0.14, 'proe': 0.03, 'espn_ownership': 96.0, 'espn_proj': 13.5, 'bye_week': 11, 'opponent': 'NO', 'implied_team_pts': 24.5, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 24, 'archetype': 'Electric YAC/Elusive Starter'},
    {'id': 'wr-ladd', 'name': 'Ladd McConkey', 'position': 'WR', 'team': 'LAC', 'adp': 42.0, 'tier': 3, 'projected_season': 230.0, 'projected_week': 14.4, 'xfp': 14.6, 'route_participation': 0.9, 'high_value_touches': 4.2, 'red_zone_share': 0.28, 'target_share': 0.26, 'proe': -0.01, 'espn_ownership': 95.5, 'espn_proj': 13.6, 'bye_week': 5, 'opponent': 'KC', 'implied_team_pts': 21.0, 'spread': 7.0, 'wind_mph': 11, 'is_dome': False, 'opp_rank_vs_pos': 18, 'archetype': "Herbert's Favorite Separation Weapon"},
    {'id': 'wr-terry', 'name': 'Terry McLaurin', 'position': 'WR', 'team': 'WAS', 'adp': 46.0, 'tier': 3, 'projected_season': 225.0, 'projected_week': 14.0, 'xfp': 14.2, 'route_participation': 0.94, 'high_value_touches': 4.1, 'red_zone_share': 0.3, 'target_share': 0.26, 'proe': 0.04, 'espn_ownership': 96.0, 'espn_proj': 13.8, 'bye_week': 14, 'opponent': 'PHI', 'implied_team_pts': 23.5, 'spread': 8.0, 'wind_mph': 7, 'is_dome': False, 'opp_rank_vs_pos': 22, 'archetype': 'Scary Terry / Jayden Deep Connection'},
    {'id': 'te-laporta', 'name': 'Sam LaPorta', 'position': 'TE', 'team': 'DET', 'adp': 50.0, 'tier': 2, 'projected_season': 215.0, 'projected_week': 13.4, 'xfp': 13.2, 'route_participation': 0.86, 'high_value_touches': 3.4, 'red_zone_share': 0.24, 'target_share': 0.19, 'proe': 0.01, 'espn_ownership': 97.0, 'espn_proj': 13.0, 'bye_week': 5, 'opponent': 'GB', 'implied_team_pts': 27.5, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 19, 'archetype': 'High-Powered Offense TE Target'},
    {'id': 'te-kelce', 'name': 'Travis Kelce', 'position': 'TE', 'team': 'KC', 'adp': 52.0, 'tier': 2, 'projected_season': 210.0, 'projected_week': 13.1, 'xfp': 13.0, 'route_participation': 0.82, 'high_value_touches': 3.3, 'red_zone_share': 0.26, 'target_share': 0.2, 'proe': 0.09, 'espn_ownership': 97.5, 'espn_proj': 13.2, 'bye_week': 6, 'opponent': 'LAC', 'implied_team_pts': 28.0, 'spread': -7.0, 'wind_mph': 11, 'is_dome': False, 'opp_rank_vs_pos': 17, 'archetype': 'Veteran Playoff & Red Zone Anchor'},
    {'id': 'te-kraft', 'name': 'Tucker Kraft', 'position': 'TE', 'team': 'GB', 'adp': 115.0, 'tier': 3, 'projected_season': 185.0, 'projected_week': 11.6, 'xfp': 12.2, 'route_participation': 0.86, 'high_value_touches': 3.4, 'red_zone_share': 0.25, 'target_share': 0.19, 'proe': -0.01, 'espn_ownership': 44.0, 'espn_proj': 8.5, 'bye_week': 10, 'opponent': 'DET', 'implied_team_pts': 24.5, 'spread': 3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 22, 'archetype': 'Every-Down YAC Monster TE (Arbitrage Target)'},
    {'id': 'rb-benson', 'name': 'Trey Benson', 'position': 'RB', 'team': 'ARI', 'adp': 120.0, 'tier': 4, 'projected_season': 170.0, 'projected_week': 10.6, 'xfp': 11.8, 'route_participation': 0.48, 'high_value_touches': 3.5, 'red_zone_share': 0.28, 'target_share': 0.12, 'proe': 0.02, 'espn_ownership': 36.0, 'espn_proj': 7.2, 'bye_week': 11, 'opponent': 'SEA', 'implied_team_pts': 23.0, 'spread': 1.5, 'wind_mph': 6, 'is_dome': False, 'opp_rank_vs_pos': 26, 'archetype': 'Explosive High-Value Touch Breakout RB'},
    {'id': 'wr-mcmillan', 'name': 'Jalen McMillan', 'position': 'WR', 'team': 'TB', 'adp': 135.0, 'tier': 4, 'projected_season': 175.0, 'projected_week': 10.9, 'xfp': 12.5, 'route_participation': 0.89, 'high_value_touches': 3.8, 'red_zone_share': 0.26, 'target_share': 0.22, 'proe': 0.03, 'espn_ownership': 26.0, 'espn_proj': 7.5, 'bye_week': 11, 'opponent': 'NO', 'implied_team_pts': 24.5, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 24, 'archetype': 'Route-Spike Sleeper Target'},
    {'id': 'wr-downs', 'name': 'Josh Downs', 'position': 'WR', 'team': 'IND', 'adp': 125.0, 'tier': 4, 'projected_season': 172.0, 'projected_week': 10.8, 'xfp': 12.8, 'route_participation': 0.88, 'high_value_touches': 3.6, 'red_zone_share': 0.24, 'target_share': 0.26, 'proe': -0.05, 'espn_ownership': 40.0, 'espn_proj': 8.0, 'bye_week': 14, 'opponent': 'HOU', 'implied_team_pts': 22.5, 'spread': 3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 20, 'archetype': 'Slot Target Funnel'},
    {'id': 'te-loveland', 'name': 'Colston Loveland', 'position': 'TE', 'team': 'CHI', 'adp': 94.0, 'tier': 3, 'projected_season': 185.0, 'projected_week': 11.6, 'xfp': 11.4, 'route_participation': 0.76, 'high_value_touches': 3.8, 'red_zone_share': 0.26, 'target_share': 0.16, 'proe': 0.04, 'espn_ownership': 78.0, 'espn_proj': 10.8, 'bye_week': 7, 'opponent': 'MIN', 'implied_team_pts': 23.5, 'spread': 2.5, 'wind_mph': 8, 'is_dome': False, 'opp_rank_vs_pos': 18, 'archetype': '2025 Top Rookie TE / Caleb Williams Seam Threat'},
    {'id': 'te-warren', 'name': 'Tyler Warren', 'position': 'TE', 'team': 'IND', 'adp': 98.0, 'tier': 3, 'projected_season': 178.0, 'projected_week': 11.1, 'xfp': 10.9, 'route_participation': 0.74, 'high_value_touches': 3.5, 'red_zone_share': 0.24, 'target_share': 0.15, 'proe': 0.01, 'espn_ownership': 72.0, 'espn_proj': 10.4, 'bye_week': 14, 'opponent': 'HOU', 'implied_team_pts': 22.0, 'spread': 3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 19, 'archetype': '2025 Do-It-All Move TE / RZ Specialist'},
    {'id': 'te-engram', 'name': 'Evan Engram', 'position': 'TE', 'team': 'DEN', 'adp': 72.0, 'tier': 3, 'projected_season': 198.0, 'projected_week': 12.4, 'xfp': 12.2, 'route_participation': 0.8, 'high_value_touches': 4.0, 'red_zone_share': 0.25, 'target_share': 0.19, 'proe': 0.03, 'espn_ownership': 92.0, 'espn_proj': 11.9, 'bye_week': 12, 'opponent': 'TEN', 'implied_team_pts': 23.0, 'spread': -2.5, 'wind_mph': 5, 'is_dome': False, 'opp_rank_vs_pos': 21, 'archetype': 'PPR Short-Area Volume TE'},
    {'id': 'te-ferguson', 'name': 'Jake Ferguson', 'position': 'TE', 'team': 'DAL', 'adp': 78.0, 'tier': 3, 'projected_season': 190.0, 'projected_week': 11.9, 'xfp': 11.8, 'route_participation': 0.78, 'high_value_touches': 3.9, 'red_zone_share': 0.27, 'target_share': 0.17, 'proe': 0.07, 'espn_ownership': 88.0, 'espn_proj': 11.5, 'bye_week': 7, 'opponent': 'NYG', 'implied_team_pts': 26.5, 'spread': -6.5, 'wind_mph': 5, 'is_dome': True, 'opp_rank_vs_pos': 20, 'archetype': 'Dak Prescott Red Zone Safety Valve'},
    {'id': 'te-njoku', 'name': 'David Njoku', 'position': 'TE', 'team': 'LAC', 'adp': 82.0, 'tier': 3, 'projected_season': 186.0, 'projected_week': 11.6, 'xfp': 11.5, 'route_participation': 0.77, 'high_value_touches': 3.7, 'red_zone_share': 0.26, 'target_share': 0.18, 'proe': 0.02, 'espn_ownership': 85.0, 'espn_proj': 11.0, 'bye_week': 10, 'opponent': 'CIN', 'implied_team_pts': 20.5, 'spread': 4.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 22, 'archetype': 'Elite Athletic YAC Target'},
    {'id': 'te-kmet', 'name': 'Cole Kmet', 'position': 'TE', 'team': 'CHI', 'adp': 112.0, 'tier': 4, 'projected_season': 155.0, 'projected_week': 9.7, 'xfp': 9.5, 'route_participation': 0.65, 'high_value_touches': 2.8, 'red_zone_share': 0.2, 'target_share': 0.13, 'proe': 0.04, 'espn_ownership': 62.0, 'espn_proj': 9.2, 'bye_week': 7, 'opponent': 'MIN', 'implied_team_pts': 23.5, 'spread': 2.5, 'wind_mph': 8, 'is_dome': False, 'opp_rank_vs_pos': 18, 'archetype': 'Red Zone Possession Veteran'},
    {'id': 'rb-jeanty', 'name': 'Ashton Jeanty', 'position': 'RB', 'team': 'LV', 'adp': 24.0, 'tier': 2, 'projected_season': 275.0, 'projected_week': 17.2, 'xfp': 16.8, 'route_participation': 0.64, 'high_value_touches': 5.2, 'red_zone_share': 0.42, 'target_share': 0.15, 'proe': -0.02, 'espn_ownership': 98.0, 'espn_proj': 16.5, 'bye_week': 10, 'opponent': 'DEN', 'implied_team_pts': 22.0, 'spread': -1.5, 'wind_mph': 7, 'is_dome': True, 'opp_rank_vs_pos': 22, 'archetype': '2025 Generation 1st-Round Bellcow (Monitoring Weekend Injury)'},
    {'id': 'wr-burden', 'name': 'Luther Burden III', 'position': 'WR', 'team': 'NE', 'adp': 54.0, 'tier': 3, 'projected_season': 235.0, 'projected_week': 14.7, 'xfp': 14.4, 'route_participation': 0.88, 'high_value_touches': 4.3, 'red_zone_share': 0.28, 'target_share': 0.24, 'proe': 0.01, 'espn_ownership': 91.0, 'espn_proj': 14.2, 'bye_week': 14, 'opponent': 'NYJ', 'implied_team_pts': 20.0, 'spread': 5.5, 'wind_mph': 11, 'is_dome': False, 'opp_rank_vs_pos': 23, 'archetype': 'Explosive Slot Weapon & YAC Creator'},
    {'id': 'wr-odunze', 'name': 'Rome Odunze', 'position': 'WR', 'team': 'CHI', 'adp': 62.0, 'tier': 3, 'projected_season': 228.0, 'projected_week': 14.2, 'xfp': 13.9, 'route_participation': 0.9, 'high_value_touches': 4.1, 'red_zone_share': 0.29, 'target_share': 0.22, 'proe': 0.04, 'espn_ownership': 93.0, 'espn_proj': 13.8, 'bye_week': 7, 'opponent': 'MIN', 'implied_team_pts': 23.5, 'spread': 2.5, 'wind_mph': 8, 'is_dome': False, 'opp_rank_vs_pos': 21, 'archetype': 'Year 2 Leap Candidate / Caleb Williams Alpha'},
    {'id': 'def-vikings', 'name': 'Minnesota Vikings D/ST', 'position': 'DEF', 'team': 'MIN', 'adp': 125.0, 'tier': 1, 'projected_season': 145.0, 'projected_week': 9.2, 'xfp': 9.4, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 92.0, 'espn_proj': 8.5, 'bye_week': 6, 'opponent': 'CHI', 'implied_team_pts': 24.5, 'spread': -2.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 31, 'archetype': 'Flores Blitz / Sack & Turnover Anchor'},
    {'id': 'def-eagles', 'name': 'Philadelphia Eagles D/ST', 'position': 'DEF', 'team': 'PHI', 'adp': 130.0, 'tier': 1, 'projected_season': 140.0, 'projected_week': 8.8, 'xfp': 8.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 90.0, 'espn_proj': 8.2, 'bye_week': 5, 'opponent': 'WAS', 'implied_team_pts': 28.5, 'spread': -8.0, 'wind_mph': 7, 'is_dome': False, 'opp_rank_vs_pos': 26, 'archetype': 'Elite Pass Rush Unit'},
    {'id': 'k-aubrey', 'name': 'Brandon Aubrey', 'position': 'K', 'team': 'DAL', 'adp': 120.0, 'tier': 1, 'projected_season': 160.0, 'projected_week': 10.0, 'xfp': 9.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 99.0, 'espn_proj': 9.5, 'bye_week': 7, 'opponent': 'NYG', 'implied_team_pts': 26.5, 'spread': -6.5, 'wind_mph': 5, 'is_dome': True, 'opp_rank_vs_pos': 25, 'archetype': 'Elite 50+ Yard Weapon'},
    {'id': 'k-boswell', 'name': 'Chris Boswell', 'position': 'K', 'team': 'PIT', 'adp': 135.0, 'tier': 1, 'projected_season': 150.0, 'projected_week': 9.4, 'xfp': 9.2, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 94.0, 'espn_proj': 8.8, 'bye_week': 9, 'opponent': 'CIN', 'implied_team_pts': 23.0, 'spread': 3.5, 'wind_mph': 6, 'is_dome': False, 'opp_rank_vs_pos': 22, 'archetype': 'High-Volume Field Goal Specialist'},
    {'id': 'qb-mahomes', 'name': 'Patrick Mahomes', 'position': 'QB', 'team': 'KC', 'adp': 50.0, 'tier': 2, 'projected_season': 340.0, 'projected_week': 21.2, 'xfp': 20.5, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.08, 'espn_ownership': 99.8, 'espn_proj': 20.8, 'bye_week': 6, 'opponent': 'LAC', 'implied_team_pts': 26.5, 'spread': -4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 20, 'archetype': 'Generational Pass-Volume Maestro'},
    {'id': 'qb-burrow', 'name': 'Joe Burrow', 'position': 'QB', 'team': 'CIN', 'adp': 55.0, 'tier': 2, 'projected_season': 338.0, 'projected_week': 21.1, 'xfp': 20.4, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.09, 'espn_ownership': 99.6, 'espn_proj': 20.5, 'bye_week': 12, 'opponent': 'PIT', 'implied_team_pts': 26.5, 'spread': -3.5, 'wind_mph': 6, 'is_dome': False, 'opp_rank_vs_pos': 18, 'archetype': 'High-Volume Pocket Passer & Deep Ball Sniper'},
    {'id': 'qb-stroud', 'name': 'C.J. Stroud', 'position': 'QB', 'team': 'HOU', 'adp': 65.0, 'tier': 2, 'projected_season': 325.0, 'projected_week': 20.3, 'xfp': 19.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.06, 'espn_ownership': 98.9, 'espn_proj': 19.8, 'bye_week': 14, 'opponent': 'IND', 'implied_team_pts': 26.0, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 24, 'archetype': 'Explosive Downfield Distributor'},
    {'id': 'qb-kyler', 'name': 'Kyler Murray', 'position': 'QB', 'team': 'MIN', 'adp': 68.0, 'tier': 2, 'projected_season': 320.0, 'projected_week': 20.0, 'xfp': 19.5, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.01, 'espn_ownership': 98.0, 'espn_proj': 19.4, 'bye_week': 11, 'opponent': 'SF', 'implied_team_pts': 23.5, 'spread': 6.0, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 17, 'archetype': 'Vikings Starting QB / Justin Jefferson Pass Funnel'},
    {'id': 'qb-love', 'name': 'Jordan Love', 'position': 'QB', 'team': 'GB', 'adp': 75.0, 'tier': 3, 'projected_season': 315.0, 'projected_week': 19.7, 'xfp': 19.2, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.04, 'espn_ownership': 96.0, 'espn_proj': 19.0, 'bye_week': 10, 'opponent': 'DET', 'implied_team_pts': 25.0, 'spread': 3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 21, 'archetype': 'Red Zone TD Machine'},
    {'id': 'qb-baker', 'name': 'Baker Mayfield', 'position': 'QB', 'team': 'TB', 'adp': 80.0, 'tier': 3, 'projected_season': 310.0, 'projected_week': 19.4, 'xfp': 18.9, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.05, 'espn_ownership': 94.0, 'espn_proj': 18.8, 'bye_week': 11, 'opponent': 'NO', 'implied_team_pts': 25.5, 'spread': -4.0, 'wind_mph': 5, 'is_dome': False, 'opp_rank_vs_pos': 23, 'archetype': 'Gunslinger Volume Floor'},
    {'id': 'qb-purdy', 'name': 'Brock Purdy', 'position': 'QB', 'team': 'SF', 'adp': 85.0, 'tier': 3, 'projected_season': 305.0, 'projected_week': 19.1, 'xfp': 18.6, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': -0.02, 'espn_ownership': 93.0, 'espn_proj': 18.5, 'bye_week': 9, 'opponent': 'ARI', 'implied_team_pts': 26.0, 'spread': -6.0, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 24, 'archetype': 'Hyper-Efficient Play-Action Sniper'},
    {'id': 'qb-caleb', 'name': 'Caleb Williams', 'position': 'QB', 'team': 'CHI', 'adp': 88.0, 'tier': 3, 'projected_season': 300.0, 'projected_week': 18.8, 'xfp': 18.4, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.04, 'espn_ownership': 91.0, 'espn_proj': 18.0, 'bye_week': 7, 'opponent': 'MIN', 'implied_team_pts': 23.5, 'spread': 2.5, 'wind_mph': 8, 'is_dome': False, 'opp_rank_vs_pos': 19, 'archetype': 'Year 2 Breakout Playmaker'},
    {'id': 'qb-goff', 'name': 'Jared Goff', 'position': 'QB', 'team': 'DET', 'adp': 92.0, 'tier': 3, 'projected_season': 295.0, 'projected_week': 18.4, 'xfp': 18.0, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.01, 'espn_ownership': 89.0, 'espn_proj': 17.9, 'bye_week': 5, 'opponent': 'GB', 'implied_team_pts': 27.5, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 22, 'archetype': 'Dome Environment Volume Machine'},
    {'id': 'qb-dak', 'name': 'Dak Prescott', 'position': 'QB', 'team': 'DAL', 'adp': 96.0, 'tier': 3, 'projected_season': 290.0, 'projected_week': 18.1, 'xfp': 17.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.07, 'espn_ownership': 88.0, 'espn_proj': 17.6, 'bye_week': 7, 'opponent': 'NYG', 'implied_team_pts': 26.5, 'spread': -6.5, 'wind_mph': 5, 'is_dome': True, 'opp_rank_vs_pos': 26, 'archetype': 'High-Volume Pass Heavy Scheme'},
    {'id': 'qb-arich', 'name': 'Anthony Richardson', 'position': 'QB', 'team': 'IND', 'adp': 100.0, 'tier': 4, 'projected_season': 285.0, 'projected_week': 17.8, 'xfp': 18.2, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': -0.03, 'espn_ownership': 85.0, 'espn_proj': 17.2, 'bye_week': 14, 'opponent': 'HOU', 'implied_team_pts': 22.0, 'spread': 3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 19, 'archetype': 'Elite Athletic Rushing Boom/Bust'},
    {'id': 'qb-nix', 'name': 'Bo Nix', 'position': 'QB', 'team': 'DEN', 'adp': 105.0, 'tier': 4, 'projected_season': 280.0, 'projected_week': 17.5, 'xfp': 17.2, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.02, 'espn_ownership': 82.0, 'espn_proj': 16.9, 'bye_week': 14, 'opponent': 'LVR', 'implied_team_pts': 23.5, 'spread': -2.5, 'wind_mph': 5, 'is_dome': False, 'opp_rank_vs_pos': 25, 'archetype': 'Sean Payton Rushing Scrambler'},
    {'id': 'qb-tua', 'name': 'Tua Tagovailoa', 'position': 'QB', 'team': 'ATL', 'adp': 108.0, 'tier': 4, 'projected_season': 278.0, 'projected_week': 17.4, 'xfp': 17.2, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.03, 'espn_ownership': 82.0, 'espn_proj': 16.9, 'bye_week': 12, 'opponent': 'CAR', 'implied_team_pts': 25.5, 'spread': -4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 30, 'archetype': 'Falcons Starting QB / Fresh Start with London, Pitts & Bijan'},
    {'id': 'qb-willis', 'name': 'Malik Willis', 'position': 'QB', 'team': 'MIA', 'adp': 115.0, 'tier': 4, 'projected_season': 272.0, 'projected_week': 17.0, 'xfp': 16.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.02, 'espn_ownership': 72.0, 'espn_proj': 16.2, 'bye_week': 6, 'opponent': 'BUF', 'implied_team_pts': 21.5, 'spread': 7.0, 'wind_mph': 12, 'is_dome': False, 'opp_rank_vs_pos': 15, 'archetype': 'Dolphins Starting Dual-Threat QB / Explosive Rushing Scrambler'},
    {'id': 'qb-penix', 'name': 'Michael Penix Jr.', 'position': 'QB', 'team': 'ATL', 'adp': 142.0, 'tier': 5, 'projected_season': 210.0, 'projected_week': 13.1, 'xfp': 13.0, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.02, 'espn_ownership': 40.0, 'espn_proj': 12.5, 'bye_week': 12, 'opponent': 'CAR', 'implied_team_pts': 25.5, 'spread': -4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 30, 'archetype': 'Falcons 1st-Round Big-Arm QB (Recovering from Knee Surgery)'},
    {'id': 'qb-herbert', 'name': 'Justin Herbert', 'position': 'QB', 'team': 'LAC', 'adp': 112.0, 'tier': 4, 'projected_season': 272.0, 'projected_week': 17.0, 'xfp': 16.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': -0.06, 'espn_ownership': 78.0, 'espn_proj': 16.5, 'bye_week': 5, 'opponent': 'KC', 'implied_team_pts': 21.0, 'spread': 4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 16, 'archetype': 'Elite Arm in Harbaugh Run Scheme'},
    {'id': 'qb-maye', 'name': 'Drake Maye', 'position': 'QB', 'team': 'NE', 'adp': 115.0, 'tier': 4, 'projected_season': 268.0, 'projected_week': 16.8, 'xfp': 16.5, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.01, 'espn_ownership': 70.0, 'espn_proj': 16.0, 'bye_week': 14, 'opponent': 'NYJ', 'implied_team_pts': 20.0, 'spread': 5.5, 'wind_mph': 11, 'is_dome': False, 'opp_rank_vs_pos': 20, 'archetype': 'Big-Arm Rushing Upside Rookie'},
    {'id': 'qb-tlaw', 'name': 'Trevor Lawrence', 'position': 'QB', 'team': 'JAX', 'adp': 118.0, 'tier': 4, 'projected_season': 265.0, 'projected_week': 16.5, 'xfp': 16.4, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.03, 'espn_ownership': 68.0, 'espn_proj': 15.9, 'bye_week': 12, 'opponent': 'TEN', 'implied_team_pts': 23.5, 'spread': -2.5, 'wind_mph': 5, 'is_dome': False, 'opp_rank_vs_pos': 22, 'archetype': 'Gunslinger with BTJ Deep Target'},
    {'id': 'qb-stafford', 'name': 'Matthew Stafford', 'position': 'QB', 'team': 'LAR', 'adp': 122.0, 'tier': 4, 'projected_season': 260.0, 'projected_week': 16.2, 'xfp': 16.0, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.02, 'espn_ownership': 65.0, 'espn_proj': 15.6, 'bye_week': 6, 'opponent': 'SF', 'implied_team_pts': 22.0, 'spread': 4.0, 'wind_mph': 4, 'is_dome': False, 'opp_rank_vs_pos': 18, 'archetype': 'Puka & Kupp Volume Distributor'},
    {'id': 'qb-geno', 'name': 'Geno Smith', 'position': 'QB', 'team': 'NYJ', 'adp': 125.0, 'tier': 4, 'projected_season': 258.0, 'projected_week': 16.1, 'xfp': 15.9, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.06, 'espn_ownership': 60.0, 'espn_proj': 15.4, 'bye_week': 10, 'opponent': 'ARI', 'implied_team_pts': 24.5, 'spread': -3.5, 'wind_mph': 8, 'is_dome': False, 'opp_rank_vs_pos': 24, 'archetype': 'Ryan Grubb High-Volume Passer'},
    {'id': 'qb-kirk', 'name': 'Kirk Cousins', 'position': 'QB', 'team': 'LV', 'adp': 128.0, 'tier': 4, 'projected_season': 255.0, 'projected_week': 15.9, 'xfp': 15.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.01, 'espn_ownership': 55.0, 'espn_proj': 15.2, 'bye_week': 12, 'opponent': 'CAR', 'implied_team_pts': 25.5, 'spread': -4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 30, 'archetype': 'Dome Pocket Passer with London & Bijan'},
    {'id': 'qb-rodgers', 'name': 'Aaron Rodgers', 'position': 'QB', 'team': 'PIT', 'adp': 132.0, 'tier': 5, 'projected_season': 250.0, 'projected_week': 15.6, 'xfp': 15.5, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.02, 'espn_ownership': 50.0, 'espn_proj': 15.0, 'bye_week': 12, 'opponent': 'NE', 'implied_team_pts': 23.0, 'spread': -5.5, 'wind_mph': 11, 'is_dome': False, 'opp_rank_vs_pos': 21, 'archetype': 'Veteran Pocket Commander'},
    {'id': 'qb-russell', 'name': 'Russell Wilson', 'position': 'QB', 'team': 'PIT', 'adp': 136.0, 'tier': 5, 'projected_season': 245.0, 'projected_week': 15.3, 'xfp': 15.2, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': -0.04, 'espn_ownership': 45.0, 'espn_proj': 14.8, 'bye_week': 9, 'opponent': 'CIN', 'implied_team_pts': 23.0, 'spread': 3.5, 'wind_mph': 6, 'is_dome': False, 'opp_rank_vs_pos': 22, 'archetype': 'Deep Ball Moonball Specialist'},
    {'id': 'qb-bryce', 'name': 'Bryce Young', 'position': 'QB', 'team': 'CAR', 'adp': 140.0, 'tier': 5, 'projected_season': 240.0, 'projected_week': 15.0, 'xfp': 15.0, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.01, 'espn_ownership': 38.0, 'espn_proj': 14.5, 'bye_week': 11, 'opponent': 'ATL', 'implied_team_pts': 21.0, 'spread': 4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 25, 'archetype': 'Dave Canales Resurgence Candidate'},
    {'id': 'qb-levis', 'name': 'Will Levis', 'position': 'QB', 'team': 'TEN', 'adp': 144.0, 'tier': 5, 'projected_season': 235.0, 'projected_week': 14.7, 'xfp': 14.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.02, 'espn_ownership': 30.0, 'espn_proj': 14.2, 'bye_week': 5, 'opponent': 'JAX', 'implied_team_pts': 20.5, 'spread': 2.5, 'wind_mph': 5, 'is_dome': False, 'opp_rank_vs_pos': 27, 'archetype': 'Big Cannon Arm Downfield'},
    {'id': 'qb-shough', 'name': 'Tyler Shough', 'position': 'QB', 'team': 'NO', 'adp': 146.0, 'tier': 5, 'projected_season': 235.0, 'projected_week': 14.7, 'xfp': 14.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.01, 'espn_ownership': 32.0, 'espn_proj': 14.2, 'bye_week': 12, 'opponent': 'TB', 'implied_team_pts': 21.5, 'spread': 4.0, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 23, 'archetype': 'Saints Starting QB / Big Arm Starter in Superdome'},
    {'id': 'qb-watson', 'name': 'Deshaun Watson', 'position': 'QB', 'team': 'CLE', 'adp': 150.0, 'tier': 5, 'projected_season': 225.0, 'projected_week': 14.0, 'xfp': 14.2, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.01, 'espn_ownership': 25.0, 'espn_proj': 13.8, 'bye_week': 10, 'opponent': 'BAL', 'implied_team_pts': 20.5, 'spread': 6.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 16, 'archetype': 'Injury Comeback Quarterback'},
    {'id': 'qb-camward', 'name': 'Cam Ward', 'position': 'QB', 'team': 'TEN', 'adp': 152.0, 'tier': 5, 'projected_season': 230.0, 'projected_week': 14.4, 'xfp': 14.6, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.02, 'espn_ownership': 35.0, 'espn_proj': 14.0, 'bye_week': 11, 'opponent': 'DAL', 'implied_team_pts': 21.0, 'spread': 6.5, 'wind_mph': 5, 'is_dome': True, 'opp_rank_vs_pos': 20, 'archetype': '2025 Dynamic Rookie Playmaker'},
    {'id': 'qb-shedeur', 'name': 'Shedeur Sanders', 'position': 'QB', 'team': 'CLE', 'adp': 155.0, 'tier': 5, 'projected_season': 228.0, 'projected_week': 14.2, 'xfp': 14.4, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.03, 'espn_ownership': 32.0, 'espn_proj': 13.9, 'bye_week': 10, 'opponent': 'DEN', 'implied_team_pts': 22.0, 'spread': -1.5, 'wind_mph': 7, 'is_dome': True, 'opp_rank_vs_pos': 18, 'archetype': '2025 Accurate Pocket Rookie'},
    {'id': 'qb-djones', 'name': 'Daniel Jones', 'position': 'QB', 'team': 'IND', 'adp': 160.0, 'tier': 5, 'projected_season': 200.0, 'projected_week': 12.5, 'xfp': 12.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': -0.01, 'espn_ownership': 15.0, 'espn_proj': 12.0, 'bye_week': 11, 'opponent': 'DAL', 'implied_team_pts': 20.0, 'spread': 7.0, 'wind_mph': 5, 'is_dome': True, 'opp_rank_vs_pos': 15, 'archetype': 'Veteran Scrambler Backup'},
    {'id': 'k-butker', 'name': 'Harrison Butker', 'position': 'K', 'team': 'KC', 'adp': 128.0, 'tier': 1, 'projected_season': 154.0, 'projected_week': 9.6, 'xfp': 9.4, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 95.0, 'espn_proj': 9.2, 'bye_week': 6, 'opponent': 'LAC', 'implied_team_pts': 26.5, 'spread': -4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 20, 'archetype': 'High Scoring Offense Kicker'},
    {'id': 'k-tucker', 'name': 'Justin Tucker', 'position': 'K', 'team': 'BAL', 'adp': 130.0, 'tier': 1, 'projected_season': 152.0, 'projected_week': 9.5, 'xfp': 9.3, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 94.0, 'espn_proj': 9.1, 'bye_week': 14, 'opponent': 'CLE', 'implied_team_pts': 27.5, 'spread': -6.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 21, 'archetype': 'Legendary Clutch Specialist'},
    {'id': 'k-fairbairn', 'name': "Ka'imi Fairbairn", 'position': 'K', 'team': 'HOU', 'adp': 134.0, 'tier': 1, 'projected_season': 148.0, 'projected_week': 9.2, 'xfp': 9.1, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 91.0, 'espn_proj': 8.9, 'bye_week': 14, 'opponent': 'IND', 'implied_team_pts': 26.0, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 24, 'archetype': 'Dome Scoring Weapon'},
    {'id': 'k-dicker', 'name': 'Cameron Dicker', 'position': 'K', 'team': 'LAC', 'adp': 137.0, 'tier': 1, 'projected_season': 145.0, 'projected_week': 9.1, 'xfp': 9.0, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 88.0, 'espn_proj': 8.8, 'bye_week': 5, 'opponent': 'KC', 'implied_team_pts': 21.0, 'spread': 4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 19, 'archetype': 'High Accuracy Specialist'},
    {'id': 'k-moody', 'name': 'Jake Moody', 'position': 'K', 'team': 'SF', 'adp': 139.0, 'tier': 1, 'projected_season': 144.0, 'projected_week': 9.0, 'xfp': 8.9, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 86.0, 'espn_proj': 8.7, 'bye_week': 9, 'opponent': 'ARI', 'implied_team_pts': 26.0, 'spread': -6.0, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 23, 'archetype': '49ers High-Powered Offense'},
    {'id': 'k-elliott', 'name': 'Jake Elliott', 'position': 'K', 'team': 'PHI', 'adp': 141.0, 'tier': 1, 'projected_season': 142.0, 'projected_week': 8.9, 'xfp': 8.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 85.0, 'espn_proj': 8.6, 'bye_week': 5, 'opponent': 'WAS', 'implied_team_pts': 28.5, 'spread': -8.0, 'wind_mph': 7, 'is_dome': False, 'opp_rank_vs_pos': 26, 'archetype': 'High XP & FG Floor'},
    {'id': 'k-bass', 'name': 'Tyler Bass', 'position': 'K', 'team': 'BUF', 'adp': 143.0, 'tier': 1, 'projected_season': 140.0, 'projected_week': 8.8, 'xfp': 8.7, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 82.0, 'espn_proj': 8.5, 'bye_week': 12, 'opponent': 'MIA', 'implied_team_pts': 28.0, 'spread': -7.0, 'wind_mph': 12, 'is_dome': False, 'opp_rank_vs_pos': 21, 'archetype': 'Bills Scoring Floor'},
    {'id': 'k-koo', 'name': 'Younghoe Koo', 'position': 'K', 'team': 'ATL', 'adp': 145.0, 'tier': 1, 'projected_season': 138.0, 'projected_week': 8.6, 'xfp': 8.6, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 80.0, 'espn_proj': 8.4, 'bye_week': 12, 'opponent': 'CAR', 'implied_team_pts': 25.5, 'spread': -4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 28, 'archetype': 'Dome Environment Field Goal Volume'},
    {'id': 'k-sanders', 'name': 'Jason Sanders', 'position': 'K', 'team': 'NYJ', 'adp': 147.0, 'tier': 1, 'projected_season': 135.0, 'projected_week': 8.4, 'xfp': 8.4, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 75.0, 'espn_proj': 8.2, 'bye_week': 6, 'opponent': 'BUF', 'implied_team_pts': 21.5, 'spread': 7.0, 'wind_mph': 12, 'is_dome': False, 'opp_rank_vs_pos': 18, 'archetype': 'Long Range Scoring Weapon'},
    {'id': 'k-mcpherson', 'name': 'Evan McPherson', 'position': 'K', 'team': 'CIN', 'adp': 149.0, 'tier': 2, 'projected_season': 134.0, 'projected_week': 8.4, 'xfp': 8.4, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 73.0, 'espn_proj': 8.1, 'bye_week': 12, 'opponent': 'PIT', 'implied_team_pts': 26.5, 'spread': -3.5, 'wind_mph': 6, 'is_dome': False, 'opp_rank_vs_pos': 20, 'archetype': 'High-Scoring Bengals Offense'},
    {'id': 'k-mclaughlin', 'name': 'Chase McLaughlin', 'position': 'K', 'team': 'TB', 'adp': 151.0, 'tier': 2, 'projected_season': 132.0, 'projected_week': 8.2, 'xfp': 8.2, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 68.0, 'espn_proj': 8.0, 'bye_week': 11, 'opponent': 'NO', 'implied_team_pts': 25.5, 'spread': -4.0, 'wind_mph': 5, 'is_dome': False, 'opp_rank_vs_pos': 22, 'archetype': '50+ Yard Accuracy Leader'},
    {'id': 'k-lutz', 'name': 'Wil Lutz', 'position': 'K', 'team': 'DEN', 'adp': 153.0, 'tier': 2, 'projected_season': 130.0, 'projected_week': 8.1, 'xfp': 8.1, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 65.0, 'espn_proj': 7.9, 'bye_week': 14, 'opponent': 'LVR', 'implied_team_pts': 23.5, 'spread': -2.5, 'wind_mph': 5, 'is_dome': False, 'opp_rank_vs_pos': 24, 'archetype': 'Mile High Altitude Field Goals'},
    {'id': 'k-hopkins', 'name': 'Dustin Hopkins', 'position': 'K', 'team': 'CLE', 'adp': 155.0, 'tier': 2, 'projected_season': 128.0, 'projected_week': 8.0, 'xfp': 8.0, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 60.0, 'espn_proj': 7.8, 'bye_week': 10, 'opponent': 'BAL', 'implied_team_pts': 20.5, 'spread': 6.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 19, 'archetype': 'Long Range FG Specialist'},
    {'id': 'k-santos', 'name': 'Cairo Santos', 'position': 'K', 'team': 'CHI', 'adp': 157.0, 'tier': 2, 'projected_season': 126.0, 'projected_week': 7.9, 'xfp': 7.9, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 55.0, 'espn_proj': 7.7, 'bye_week': 7, 'opponent': 'MIN', 'implied_team_pts': 23.5, 'spread': 2.5, 'wind_mph': 8, 'is_dome': False, 'opp_rank_vs_pos': 21, 'archetype': 'Steady Soldier Field Veteran'},
    {'id': 'k-grupe', 'name': 'Blake Grupe', 'position': 'K', 'team': 'IND', 'adp': 159.0, 'tier': 3, 'projected_season': 124.0, 'projected_week': 7.8, 'xfp': 7.7, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 48.0, 'espn_proj': 7.6, 'bye_week': 12, 'opponent': 'TB', 'implied_team_pts': 21.5, 'spread': 4.0, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 20, 'archetype': 'Superdome Kicker'},
    {'id': 'k-pineiro', 'name': 'Eddy Pineiro', 'position': 'K', 'team': 'SF', 'adp': 161.0, 'tier': 3, 'projected_season': 122.0, 'projected_week': 7.6, 'xfp': 7.6, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 40.0, 'espn_proj': 7.4, 'bye_week': 11, 'opponent': 'ATL', 'implied_team_pts': 21.0, 'spread': 4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 22, 'archetype': 'High Accuracy Percentage'},
    {'id': 'k-prater', 'name': 'Matt Prater', 'position': 'K', 'team': 'ARI', 'adp': 163.0, 'tier': 3, 'projected_season': 120.0, 'projected_week': 7.5, 'xfp': 7.5, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 35.0, 'espn_proj': 7.3, 'bye_week': 11, 'opponent': 'SF', 'implied_team_pts': 23.5, 'spread': 6.0, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 18, 'archetype': 'Veteran Cannon Leg'},
    {'id': 'k-joseph', 'name': 'Greg Joseph', 'position': 'K', 'team': 'NYG', 'adp': 165.0, 'tier': 3, 'projected_season': 118.0, 'projected_week': 7.4, 'xfp': 7.4, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 30.0, 'espn_proj': 7.1, 'bye_week': 11, 'opponent': 'DAL', 'implied_team_pts': 21.0, 'spread': 6.5, 'wind_mph': 5, 'is_dome': True, 'opp_rank_vs_pos': 19, 'archetype': 'FG Volume Option'},
    {'id': 'def-broncos', 'name': 'Denver Broncos D/ST', 'position': 'DEF', 'team': 'DEN', 'adp': 129.0, 'tier': 1, 'projected_season': 138.0, 'projected_week': 8.6, 'xfp': 8.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 95.0, 'espn_proj': 8.4, 'bye_week': 14, 'opponent': 'LVR', 'implied_team_pts': 23.5, 'spread': -2.5, 'wind_mph': 5, 'is_dome': False, 'opp_rank_vs_pos': 29, 'archetype': 'Vance Joseph High Pressure Sacks & Surtain Lock'},
    {'id': 'def-steelers', 'name': 'Pittsburgh Steelers D/ST', 'position': 'DEF', 'team': 'PIT', 'adp': 131.0, 'tier': 1, 'projected_season': 136.0, 'projected_week': 8.5, 'xfp': 8.7, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 94.0, 'espn_proj': 8.3, 'bye_week': 9, 'opponent': 'CIN', 'implied_team_pts': 23.0, 'spread': 3.5, 'wind_mph': 6, 'is_dome': False, 'opp_rank_vs_pos': 26, 'archetype': 'TJ Watt Strip-Sack & Turnover Heavy'},
    {'id': 'def-ravens', 'name': 'Baltimore Ravens D/ST', 'position': 'DEF', 'team': 'BAL', 'adp': 133.0, 'tier': 2, 'projected_season': 134.0, 'projected_week': 8.4, 'xfp': 8.5, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 92.0, 'espn_proj': 8.2, 'bye_week': 14, 'opponent': 'CLE', 'implied_team_pts': 27.5, 'spread': -6.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 27, 'archetype': 'Physical Run Stuff & Roquan Smith Anchor'},
    {'id': 'def-49ers', 'name': 'San Francisco 49ers D/ST', 'position': 'DEF', 'team': 'SF', 'adp': 135.0, 'tier': 2, 'projected_season': 132.0, 'projected_week': 8.3, 'xfp': 8.4, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 90.0, 'espn_proj': 8.0, 'bye_week': 9, 'opponent': 'ARI', 'implied_team_pts': 26.0, 'spread': -6.0, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 24, 'archetype': 'Nick Bosa Pass Rush & Warner Coverage'},
    {'id': 'def-texans', 'name': 'Houston Texans D/ST', 'position': 'DEF', 'team': 'HOU', 'adp': 138.0, 'tier': 2, 'projected_season': 130.0, 'projected_week': 8.1, 'xfp': 8.3, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 88.0, 'espn_proj': 7.9, 'bye_week': 14, 'opponent': 'IND', 'implied_team_pts': 26.0, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 25, 'archetype': 'DeMeco Ryans High-Pressure Defense'},
    {'id': 'def-jets', 'name': 'New York Jets D/ST', 'position': 'DEF', 'team': 'NYJ', 'adp': 140.0, 'tier': 2, 'projected_season': 128.0, 'projected_week': 8.0, 'xfp': 8.1, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 85.0, 'espn_proj': 7.8, 'bye_week': 12, 'opponent': 'NE', 'implied_team_pts': 23.0, 'spread': -5.5, 'wind_mph': 11, 'is_dome': False, 'opp_rank_vs_pos': 26, 'archetype': 'Sauce Gardner Lockdown Secondary'},
    {'id': 'def-lions', 'name': 'Detroit Lions D/ST', 'position': 'DEF', 'team': 'DET', 'adp': 142.0, 'tier': 2, 'projected_season': 126.0, 'projected_week': 7.9, 'xfp': 8.0, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 84.0, 'espn_proj': 7.7, 'bye_week': 5, 'opponent': 'GB', 'implied_team_pts': 27.5, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 22, 'archetype': 'Aidan Hutchinson Edge Rush & Aggressive Front'},
    {'id': 'def-chiefs', 'name': 'Kansas City Chiefs D/ST', 'position': 'DEF', 'team': 'KC', 'adp': 144.0, 'tier': 2, 'projected_season': 125.0, 'projected_week': 7.8, 'xfp': 7.9, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 82.0, 'espn_proj': 7.6, 'bye_week': 6, 'opponent': 'LAC', 'implied_team_pts': 26.5, 'spread': -4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 23, 'archetype': 'Spagnuolo Blitz Package'},
    {'id': 'def-bills', 'name': 'Buffalo Bills D/ST', 'position': 'DEF', 'team': 'BUF', 'adp': 146.0, 'tier': 3, 'projected_season': 122.0, 'projected_week': 7.6, 'xfp': 7.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 80.0, 'espn_proj': 7.5, 'bye_week': 12, 'opponent': 'MIA', 'implied_team_pts': 28.0, 'spread': -7.0, 'wind_mph': 12, 'is_dome': False, 'opp_rank_vs_pos': 21, 'archetype': 'McDermott Discipline & Turnover Ball'},
    {'id': 'def-packers', 'name': 'Green Bay Packers D/ST', 'position': 'DEF', 'team': 'GB', 'adp': 148.0, 'tier': 3, 'projected_season': 120.0, 'projected_week': 7.5, 'xfp': 7.6, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 78.0, 'espn_proj': 7.3, 'bye_week': 10, 'opponent': 'DET', 'implied_team_pts': 25.0, 'spread': 3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 20, 'archetype': 'Xavier McKinney Turnover Ball Hawk'},
    {'id': 'def-chargers', 'name': 'Los Angeles Chargers D/ST', 'position': 'DEF', 'team': 'LAC', 'adp': 150.0, 'tier': 3, 'projected_season': 118.0, 'projected_week': 7.4, 'xfp': 7.5, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 75.0, 'espn_proj': 7.2, 'bye_week': 5, 'opponent': 'KC', 'implied_team_pts': 21.0, 'spread': 4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 19, 'archetype': 'Jesse Minter Defensive Mastermind'},
    {'id': 'def-bears', 'name': 'Chicago Bears D/ST', 'position': 'DEF', 'team': 'CHI', 'adp': 152.0, 'tier': 3, 'projected_season': 116.0, 'projected_week': 7.3, 'xfp': 7.4, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 70.0, 'espn_proj': 7.0, 'bye_week': 7, 'opponent': 'MIN', 'implied_team_pts': 23.5, 'spread': 2.5, 'wind_mph': 8, 'is_dome': False, 'opp_rank_vs_pos': 22, 'archetype': 'Montez Sweat Edge & High Interception Rate'},
    {'id': 'def-cowboys', 'name': 'Dallas Cowboys D/ST', 'position': 'DEF', 'team': 'DAL', 'adp': 154.0, 'tier': 3, 'projected_season': 115.0, 'projected_week': 7.2, 'xfp': 7.3, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 68.0, 'espn_proj': 6.9, 'bye_week': 7, 'opponent': 'NYG', 'implied_team_pts': 26.5, 'spread': -6.5, 'wind_mph': 5, 'is_dome': True, 'opp_rank_vs_pos': 24, 'archetype': 'Micah Parsons Sack Artist'},
    {'id': 'def-browns', 'name': 'Cleveland Browns D/ST', 'position': 'DEF', 'team': 'CLE', 'adp': 156.0, 'tier': 4, 'projected_season': 112.0, 'projected_week': 7.0, 'xfp': 7.2, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 62.0, 'espn_proj': 6.8, 'bye_week': 10, 'opponent': 'BAL', 'implied_team_pts': 20.5, 'spread': 6.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 18, 'archetype': 'Myles Garrett DPOY Pass Rush'},
    {'id': 'def-seahawks', 'name': 'Seattle Seahawks D/ST', 'position': 'DEF', 'team': 'SEA', 'adp': 158.0, 'tier': 4, 'projected_season': 110.0, 'projected_week': 6.9, 'xfp': 7.0, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 55.0, 'espn_proj': 6.7, 'bye_week': 10, 'opponent': 'ARI', 'implied_team_pts': 24.5, 'spread': -3.5, 'wind_mph': 8, 'is_dome': False, 'opp_rank_vs_pos': 21, 'archetype': 'Mike Macdonald Scheme'},
    {'id': 'def-bucs', 'name': 'Tampa Bay Buccaneers D/ST', 'position': 'DEF', 'team': 'TB', 'adp': 160.0, 'tier': 4, 'projected_season': 108.0, 'projected_week': 6.8, 'xfp': 6.9, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 50.0, 'espn_proj': 6.5, 'bye_week': 11, 'opponent': 'NO', 'implied_team_pts': 25.5, 'spread': -4.0, 'wind_mph': 5, 'is_dome': False, 'opp_rank_vs_pos': 20, 'archetype': 'Todd Bowles Blitz System'},
    {'id': 'def-dolphins', 'name': 'Miami Dolphins D/ST', 'position': 'DEF', 'team': 'MIA', 'adp': 162.0, 'tier': 4, 'projected_season': 105.0, 'projected_week': 6.6, 'xfp': 6.7, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 45.0, 'espn_proj': 6.4, 'bye_week': 6, 'opponent': 'BUF', 'implied_team_pts': 21.5, 'spread': 7.0, 'wind_mph': 12, 'is_dome': False, 'opp_rank_vs_pos': 17, 'archetype': 'Anthony Weaver Front'},
    {'id': 'def-colts', 'name': 'Indianapolis Colts D/ST', 'position': 'DEF', 'team': 'IND', 'adp': 164.0, 'tier': 4, 'projected_season': 102.0, 'projected_week': 6.4, 'xfp': 6.5, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.0, 'espn_ownership': 40.0, 'espn_proj': 6.2, 'bye_week': 14, 'opponent': 'HOU', 'implied_team_pts': 22.0, 'spread': 3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 18, 'archetype': 'Turnover Opportunistic Unit'},
    {'id': 'wr-jsn', 'name': 'Jaxon Smith-Njigba', 'position': 'WR', 'team': 'SEA', 'adp': 44.0, 'tier': 2, 'projected_season': 255.0, 'projected_week': 15.9, 'xfp': 16.2, 'route_participation': 0.94, 'high_value_touches': 4.8, 'red_zone_share': 0.32, 'target_share': 0.26, 'proe': 0.06, 'espn_ownership': 98.0, 'espn_proj': 15.4, 'bye_week': 10, 'opponent': 'ARI', 'implied_team_pts': 24.5, 'spread': -3.5, 'wind_mph': 8, 'is_dome': False, 'opp_rank_vs_pos': 24, 'archetype': 'Ryan Grubb Alpha Slot/Wide Target Monster'},
    {'id': 'wr-dk', 'name': 'DK Metcalf', 'position': 'WR', 'team': 'PIT', 'adp': 38.0, 'tier': 2, 'projected_season': 265.0, 'projected_week': 16.5, 'xfp': 16.8, 'route_participation': 0.93, 'high_value_touches': 5.0, 'red_zone_share': 0.36, 'target_share': 0.25, 'proe': 0.06, 'espn_ownership': 99.0, 'espn_proj': 16.0, 'bye_week': 10, 'opponent': 'ARI', 'implied_team_pts': 24.5, 'spread': -3.5, 'wind_mph': 8, 'is_dome': False, 'opp_rank_vs_pos': 24, 'archetype': 'Physical Specimen / Red Zone Alpha'},
    {'id': 'wr-flowers', 'name': 'Zay Flowers', 'position': 'WR', 'team': 'BAL', 'adp': 40.0, 'tier': 2, 'projected_season': 260.0, 'projected_week': 16.2, 'xfp': 16.0, 'route_participation': 0.92, 'high_value_touches': 4.6, 'red_zone_share': 0.28, 'target_share': 0.27, 'proe': -0.05, 'espn_ownership': 98.5, 'espn_proj': 15.8, 'bye_week': 14, 'opponent': 'CLE', 'implied_team_pts': 27.5, 'spread': -6.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 28, 'archetype': 'Lamar Jackson Alpha YAC Magnet'},
    {'id': 'wr-waddle', 'name': 'Jaylen Waddle', 'position': 'WR', 'team': 'DEN', 'adp': 42.0, 'tier': 2, 'projected_season': 252.0, 'projected_week': 15.7, 'xfp': 15.8, 'route_participation': 0.89, 'high_value_touches': 4.4, 'red_zone_share': 0.27, 'target_share': 0.24, 'proe': 0.03, 'espn_ownership': 97.0, 'espn_proj': 15.2, 'bye_week': 6, 'opponent': 'BUF', 'implied_team_pts': 21.5, 'spread': 7.0, 'wind_mph': 12, 'is_dome': False, 'opp_rank_vs_pos': 20, 'archetype': 'Elite Explosive Speed Weapon'},
    {'id': 'wr-devonta', 'name': 'DeVonta Smith', 'position': 'WR', 'team': 'PHI', 'adp': 45.0, 'tier': 2, 'projected_season': 250.0, 'projected_week': 15.6, 'xfp': 15.6, 'route_participation': 0.94, 'high_value_touches': 4.5, 'red_zone_share': 0.26, 'target_share': 0.24, 'proe': -0.04, 'espn_ownership': 97.5, 'espn_proj': 15.1, 'bye_week': 5, 'opponent': 'WAS', 'implied_team_pts': 28.5, 'spread': -8.0, 'wind_mph': 7, 'is_dome': False, 'opp_rank_vs_pos': 26, 'archetype': 'Silky Smooth Route Technician'},
    {'id': 'wr-higgins', 'name': 'Tee Higgins', 'position': 'WR', 'team': 'CIN', 'adp': 46.0, 'tier': 3, 'projected_season': 248.0, 'projected_week': 15.5, 'xfp': 15.5, 'route_participation': 0.91, 'high_value_touches': 4.6, 'red_zone_share': 0.3, 'target_share': 0.24, 'proe': 0.08, 'espn_ownership': 97.0, 'espn_proj': 15.0, 'bye_week': 12, 'opponent': 'PIT', 'implied_team_pts': 26.5, 'spread': -3.5, 'wind_mph': 6, 'is_dome': False, 'opp_rank_vs_pos': 18, 'archetype': 'Burrow Red Zone / Boundary High-Point Stud'},
    {'id': 'wr-pickens', 'name': 'George Pickens', 'position': 'WR', 'team': 'DAL', 'adp': 48.0, 'tier': 3, 'projected_season': 242.0, 'projected_week': 15.1, 'xfp': 15.2, 'route_participation': 0.95, 'high_value_touches': 4.4, 'red_zone_share': 0.33, 'target_share': 0.28, 'proe': -0.04, 'espn_ownership': 96.0, 'espn_proj': 14.8, 'bye_week': 9, 'opponent': 'CIN', 'implied_team_pts': 23.0, 'spread': 3.5, 'wind_mph': 6, 'is_dome': False, 'opp_rank_vs_pos': 22, 'archetype': 'Contested Catch & Air Yards Dominator'},
    {'id': 'wr-godwin', 'name': 'Chris Godwin', 'position': 'WR', 'team': 'TB', 'adp': 50.0, 'tier': 3, 'projected_season': 240.0, 'projected_week': 15.0, 'xfp': 15.4, 'route_participation': 0.9, 'high_value_touches': 4.5, 'red_zone_share': 0.28, 'target_share': 0.26, 'proe': 0.05, 'espn_ownership': 95.0, 'espn_proj': 14.7, 'bye_week': 11, 'opponent': 'NO', 'implied_team_pts': 25.5, 'spread': -4.0, 'wind_mph': 5, 'is_dome': False, 'opp_rank_vs_pos': 23, 'archetype': 'Slot Target Funnel PPR Machine'},
    {'id': 'wr-evans', 'name': 'Mike Evans', 'position': 'WR', 'team': 'SF', 'adp': 52.0, 'tier': 3, 'projected_season': 238.0, 'projected_week': 14.9, 'xfp': 15.0, 'route_participation': 0.88, 'high_value_touches': 4.4, 'red_zone_share': 0.35, 'target_share': 0.24, 'proe': 0.05, 'espn_ownership': 95.5, 'espn_proj': 14.5, 'bye_week': 11, 'opponent': 'NO', 'implied_team_pts': 25.5, 'spread': -4.0, 'wind_mph': 5, 'is_dome': False, 'opp_rank_vs_pos': 23, 'archetype': '1,000-Yard & 10-TD Machine'},
    {'id': 'wr-kupp', 'name': 'Cooper Kupp', 'position': 'WR', 'team': 'SEA', 'adp': 54.0, 'tier': 3, 'projected_season': 236.0, 'projected_week': 14.7, 'xfp': 15.2, 'route_participation': 0.88, 'high_value_touches': 4.3, 'red_zone_share': 0.3, 'target_share': 0.27, 'proe': 0.02, 'espn_ownership': 94.0, 'espn_proj': 14.4, 'bye_week': 6, 'opponent': 'SF', 'implied_team_pts': 22.0, 'spread': 4.0, 'wind_mph': 4, 'is_dome': False, 'opp_rank_vs_pos': 18, 'archetype': 'Triple Crown PPR Slot Legend'},
    {'id': 'wr-adams', 'name': 'Davante Adams', 'position': 'WR', 'team': 'LAR', 'adp': 56.0, 'tier': 3, 'projected_season': 235.0, 'projected_week': 14.7, 'xfp': 15.0, 'route_participation': 0.92, 'high_value_touches': 4.5, 'red_zone_share': 0.34, 'target_share': 0.26, 'proe': 0.02, 'espn_ownership': 96.0, 'espn_proj': 14.3, 'bye_week': 12, 'opponent': 'NE', 'implied_team_pts': 23.0, 'spread': -5.5, 'wind_mph': 11, 'is_dome': False, 'opp_rank_vs_pos': 21, 'archetype': 'Elite Separation Master'},
    {'id': 'wr-mcconkey', 'name': 'Ladd McConkey', 'position': 'WR', 'team': 'LAC', 'adp': 58.0, 'tier': 3, 'projected_season': 232.0, 'projected_week': 14.5, 'xfp': 14.8, 'route_participation': 0.88, 'high_value_touches': 4.2, 'red_zone_share': 0.28, 'target_share': 0.26, 'proe': -0.06, 'espn_ownership': 93.0, 'espn_proj': 14.1, 'bye_week': 5, 'opponent': 'KC', 'implied_team_pts': 21.0, 'spread': 4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 18, 'archetype': 'Harbaugh Target Vacuum & Elite Separator'},
    {'id': 'wr-worthy', 'name': 'Xavier Worthy', 'position': 'WR', 'team': 'KC', 'adp': 64.0, 'tier': 3, 'projected_season': 225.0, 'projected_week': 14.0, 'xfp': 14.2, 'route_participation': 0.86, 'high_value_touches': 4.0, 'red_zone_share': 0.26, 'target_share': 0.22, 'proe': 0.08, 'espn_ownership': 91.0, 'espn_proj': 13.6, 'bye_week': 6, 'opponent': 'LAC', 'implied_team_pts': 26.5, 'spread': -4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 20, 'archetype': '4.21 Speed Gamebreaker with Mahomes'},
    {'id': 'wr-shakir', 'name': 'Khalil Shakir', 'position': 'WR', 'team': 'BUF', 'adp': 70.0, 'tier': 3, 'projected_season': 218.0, 'projected_week': 13.6, 'xfp': 13.8, 'route_participation': 0.84, 'high_value_touches': 3.8, 'red_zone_share': 0.25, 'target_share': 0.23, 'proe': 0.03, 'espn_ownership': 88.0, 'espn_proj': 13.2, 'bye_week': 12, 'opponent': 'MIA', 'implied_team_pts': 28.0, 'spread': -7.0, 'wind_mph': 12, 'is_dome': False, 'opp_rank_vs_pos': 24, 'archetype': 'Josh Allen #1 YAC Target'},
    {'id': 'wr-jamo', 'name': 'Jameson Williams', 'position': 'WR', 'team': 'DET', 'adp': 74.0, 'tier': 3, 'projected_season': 215.0, 'projected_week': 13.4, 'xfp': 13.5, 'route_participation': 0.82, 'high_value_touches': 3.6, 'red_zone_share': 0.24, 'target_share': 0.21, 'proe': 0.01, 'espn_ownership': 86.0, 'espn_proj': 13.0, 'bye_week': 5, 'opponent': 'GB', 'implied_team_pts': 27.5, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 22, 'archetype': 'Deep Ball Field Tilter'},
    {'id': 'rb-kwalker', 'name': 'Kenneth Walker III', 'position': 'RB', 'team': 'SEA', 'adp': 26.0, 'tier': 2, 'projected_season': 262.0, 'projected_week': 16.4, 'xfp': 16.2, 'route_participation': 0.56, 'high_value_touches': 5.0, 'red_zone_share': 0.45, 'target_share': 0.12, 'proe': 0.06, 'espn_ownership': 98.8, 'espn_proj': 16.1, 'bye_week': 10, 'opponent': 'ARI', 'implied_team_pts': 24.5, 'spread': -3.5, 'wind_mph': 8, 'is_dome': False, 'opp_rank_vs_pos': 27, 'archetype': 'Home-Run Explosive Workhorse'},
    {'id': 'rb-mixon', 'name': 'Joe Mixon', 'position': 'RB', 'team': 'HOU', 'adp': 30.0, 'tier': 2, 'projected_season': 255.0, 'projected_week': 15.9, 'xfp': 15.8, 'route_participation': 0.55, 'high_value_touches': 5.1, 'red_zone_share': 0.5, 'target_share': 0.11, 'proe': 0.06, 'espn_ownership': 98.2, 'espn_proj': 15.6, 'bye_week': 14, 'opponent': 'IND', 'implied_team_pts': 26.0, 'spread': -3.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 24, 'archetype': 'Texans Touchdown Anchor'},
    {'id': 'rb-kamara', 'name': 'Alvin Kamara', 'position': 'RB', 'team': 'NO', 'adp': 33.0, 'tier': 2, 'projected_season': 252.0, 'projected_week': 15.7, 'xfp': 16.0, 'route_participation': 0.7, 'high_value_touches': 5.5, 'red_zone_share': 0.42, 'target_share': 0.2, 'proe': 0.0, 'espn_ownership': 98.0, 'espn_proj': 15.5, 'bye_week': 12, 'opponent': 'TB', 'implied_team_pts': 21.5, 'spread': 4.0, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 20, 'archetype': 'Full-PPR Target Legend'},
    {'id': 'rb-conner', 'name': 'James Conner', 'position': 'RB', 'team': 'ARI', 'adp': 36.0, 'tier': 3, 'projected_season': 245.0, 'projected_week': 15.3, 'xfp': 15.2, 'route_participation': 0.54, 'high_value_touches': 4.8, 'red_zone_share': 0.52, 'target_share': 0.1, 'proe': 0.01, 'espn_ownership': 97.0, 'espn_proj': 15.0, 'bye_week': 11, 'opponent': 'SF', 'implied_team_pts': 23.5, 'spread': 6.0, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 18, 'archetype': 'Tough YAC Rusher & Goal-Line Monster'},
    {'id': 'rb-chuba', 'name': 'Chuba Hubbard', 'position': 'RB', 'team': 'CAR', 'adp': 42.0, 'tier': 3, 'projected_season': 238.0, 'projected_week': 14.9, 'xfp': 14.8, 'route_participation': 0.58, 'high_value_touches': 4.6, 'red_zone_share': 0.46, 'target_share': 0.11, 'proe': 0.01, 'espn_ownership': 94.0, 'espn_proj': 14.4, 'bye_week': 11, 'opponent': 'ATL', 'implied_team_pts': 21.0, 'spread': 4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 25, 'archetype': 'Panthers Workhorse Extension'},
    {'id': 'rb-tracy', 'name': 'Tyrone Tracy Jr.', 'position': 'RB', 'team': 'NYG', 'adp': 52.0, 'tier': 3, 'projected_season': 226.0, 'projected_week': 14.1, 'xfp': 14.0, 'route_participation': 0.62, 'high_value_touches': 4.2, 'red_zone_share': 0.42, 'target_share': 0.14, 'proe': 0.04, 'espn_ownership': 90.0, 'espn_proj': 13.8, 'bye_week': 11, 'opponent': 'DAL', 'implied_team_pts': 21.0, 'spread': 6.5, 'wind_mph': 5, 'is_dome': True, 'opp_rank_vs_pos': 26, 'archetype': 'Converted WR / High-Volume Pass Catcher'},
    {'id': 'rb-swift', 'name': "D'Andre Swift", 'position': 'RB', 'team': 'CHI', 'adp': 55.0, 'tier': 3, 'projected_season': 222.0, 'projected_week': 13.9, 'xfp': 13.8, 'route_participation': 0.56, 'high_value_touches': 4.1, 'red_zone_share': 0.38, 'target_share': 0.12, 'proe': 0.04, 'espn_ownership': 89.0, 'espn_proj': 13.5, 'bye_week': 7, 'opponent': 'MIN', 'implied_team_pts': 23.5, 'spread': 2.5, 'wind_mph': 8, 'is_dome': False, 'opp_rank_vs_pos': 19, 'archetype': 'Bears Lead Dual-Threat Back'},
    {'id': 'te-kincaid', 'name': 'Dalton Kincaid', 'position': 'TE', 'team': 'BUF', 'adp': 66.0, 'tier': 2, 'projected_season': 210.0, 'projected_week': 13.1, 'xfp': 13.0, 'route_participation': 0.82, 'high_value_touches': 4.1, 'red_zone_share': 0.27, 'target_share': 0.21, 'proe': 0.03, 'espn_ownership': 96.0, 'espn_proj': 12.8, 'bye_week': 12, 'opponent': 'MIA', 'implied_team_pts': 28.0, 'spread': -7.0, 'wind_mph': 12, 'is_dome': False, 'opp_rank_vs_pos': 21, 'archetype': 'Josh Allen Slot/Seam Weapon'},
    {'id': 'te-mandrews', 'name': 'Mark Andrews', 'position': 'TE', 'team': 'BAL', 'adp': 68.0, 'tier': 2, 'projected_season': 208.0, 'projected_week': 13.0, 'xfp': 12.8, 'route_participation': 0.72, 'high_value_touches': 4.0, 'red_zone_share': 0.32, 'target_share': 0.19, 'proe': -0.05, 'espn_ownership': 95.0, 'espn_proj': 12.6, 'bye_week': 14, 'opponent': 'CLE', 'implied_team_pts': 27.5, 'spread': -6.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 20, 'archetype': 'Lamar Jackson Goal-Line Red Zone Monster'},
    {'id': 'te-pitts', 'name': 'Kyle Pitts', 'position': 'TE', 'team': 'ATL', 'adp': 74.0, 'tier': 3, 'projected_season': 195.0, 'projected_week': 12.2, 'xfp': 12.0, 'route_participation': 0.78, 'high_value_touches': 3.8, 'red_zone_share': 0.25, 'target_share': 0.18, 'proe': 0.01, 'espn_ownership': 92.0, 'espn_proj': 11.8, 'bye_week': 12, 'opponent': 'CAR', 'implied_team_pts': 25.5, 'spread': -4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 28, 'archetype': 'Unicorn Athletic Seam Threat'},
    {'id': 'te-goedert', 'name': 'Dallas Goedert', 'position': 'TE', 'team': 'PHI', 'adp': 80.0, 'tier': 3, 'projected_season': 188.0, 'projected_week': 11.8, 'xfp': 11.6, 'route_participation': 0.76, 'high_value_touches': 3.7, 'red_zone_share': 0.24, 'target_share': 0.17, 'proe': -0.04, 'espn_ownership': 88.0, 'espn_proj': 11.4, 'bye_week': 5, 'opponent': 'WAS', 'implied_team_pts': 28.5, 'spread': -8.0, 'wind_mph': 7, 'is_dome': False, 'opp_rank_vs_pos': 24, 'archetype': 'Eagles Middle of the Field Anchor'},
    {'id': 'te-likely', 'name': 'Isaiah Likely', 'position': 'TE', 'team': 'NYG', 'adp': 90.0, 'tier': 3, 'projected_season': 180.0, 'projected_week': 11.2, 'xfp': 11.0, 'route_participation': 0.65, 'high_value_touches': 3.5, 'red_zone_share': 0.25, 'target_share': 0.16, 'proe': -0.05, 'espn_ownership': 82.0, 'espn_proj': 10.8, 'bye_week': 14, 'opponent': 'CLE', 'implied_team_pts': 27.5, 'spread': -6.5, 'wind_mph': 9, 'is_dome': False, 'opp_rank_vs_pos': 20, 'archetype': 'Explosive Athletic Playmaker'},
    {'id': 'te-freiermuth', 'name': 'Pat Freiermuth', 'position': 'TE', 'team': 'PIT', 'adp': 96.0, 'tier': 4, 'projected_season': 172.0, 'projected_week': 10.8, 'xfp': 10.5, 'route_participation': 0.74, 'high_value_touches': 3.2, 'red_zone_share': 0.24, 'target_share': 0.16, 'proe': -0.04, 'espn_ownership': 75.0, 'espn_proj': 10.2, 'bye_week': 9, 'opponent': 'CIN', 'implied_team_pts': 23.0, 'spread': 3.5, 'wind_mph': 6, 'is_dome': False, 'opp_rank_vs_pos': 22, 'archetype': 'Red Zone Possession Target'},
    {'id': 'rb-jlove', 'name': 'Jeremiyah Love', 'position': 'RB', 'team': 'ARI', 'adp': 92.0, 'tier': 4, 'projected_season': 188.0, 'projected_week': 11.8, 'xfp': 11.8, 'route_participation': 0.56, 'high_value_touches': 3.6, 'red_zone_share': 0.3, 'target_share': 0.12, 'proe': 0.01, 'espn_ownership': 82.0, 'espn_proj': 11.4, 'bye_week': 11, 'opponent': 'SF', 'implied_team_pts': 23.5, 'spread': 6.0, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 18, 'archetype': '1st-Round Rookie Dynamic Weapon (Managing Preseason High Ankle Sprain)'},
    {'id': 'qb-willis', 'name': 'Malik Willis', 'position': 'QB', 'team': 'MIA', 'adp': 115.0, 'tier': 4, 'projected_season': 272.0, 'projected_week': 17.0, 'xfp': 16.8, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.02, 'espn_ownership': 72.0, 'espn_proj': 16.2, 'bye_week': 6, 'opponent': 'BUF', 'implied_team_pts': 21.5, 'spread': 7.0, 'wind_mph': 12, 'is_dome': False, 'opp_rank_vs_pos': 15, 'archetype': 'Dolphins Starting Dual-Threat QB / Explosive Rushing Scrambler'},
    {'id': 'qb-penix', 'name': 'Michael Penix Jr.', 'position': 'QB', 'team': 'ATL', 'adp': 142.0, 'tier': 5, 'projected_season': 210.0, 'projected_week': 13.1, 'xfp': 13.0, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.02, 'espn_ownership': 40.0, 'espn_proj': 12.5, 'bye_week': 12, 'opponent': 'CAR', 'implied_team_pts': 25.5, 'spread': -4.5, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 30, 'archetype': 'Falcons 1st-Round Big-Arm QB (Recovering from Knee Surgery)'},
    {'id': 'qb-brissett', 'name': 'Jacoby Brissett', 'position': 'QB', 'team': 'ARI', 'adp': 120.0, 'tier': 4, 'projected_season': 260.0, 'projected_week': 16.2, 'xfp': 16.0, 'route_participation': 0.0, 'high_value_touches': 0.0, 'red_zone_share': 0.0, 'target_share': 0.0, 'proe': 0.02, 'espn_ownership': 55.0, 'espn_proj': 15.5, 'bye_week': 11, 'opponent': 'SF', 'implied_team_pts': 23.5, 'spread': 6.0, 'wind_mph': 0, 'is_dome': True, 'opp_rank_vs_pos': 17, 'archetype': 'Cardinals Starting QB / Distributor to MHJ & McBride'},
]

class NFLStatsService:
    def __init__(self):
        import os
        import json
        db_path = os.path.join(os.path.dirname(__file__), "verified_nfl_database.json")
        if os.path.exists(db_path):
            with open(db_path, "r", encoding="utf-8") as f:
                verified_list = json.load(f)
            self.players_db = {p["id"]: dict(p) for p in verified_list}
            logger.info(f"Loaded {len(self.players_db)} verified live NFL players from official database.")
        else:
            self.players_db = {p["id"]: dict(p) for p in INITIAL_PLAYERS}

        for player in self.players_db.values():
            self._apply_injury_intelligence(player)

    def _apply_injury_intelligence(self, player: Dict[str, Any]) -> None:
        name = player.get("name", "")
        norm = normalize_name(name)
        status = str(player.get("injury_status", "ACTIVE")).upper()
        active_injury_statuses = {"QUESTIONABLE", "Q", "DOUBTFUL", "D", "OUT", "O", "IR", "PUP", "SUSPENDED", "CUT"}
        if norm in HEALTHY_STARTERS and status not in active_injury_statuses:
            player["injury_status"] = "ACTIVE"
            player.pop("injury_type", None)
            player.pop("injury_timeline", None)
            player.pop("injury_notes", None)
            player.pop("injury_impact", None)
            return

        inj_info = get_injury_details(name, player.get("injury_status"), player.get("injury_body_part"), player.get("injury_notes"))
        if inj_info:
            player["injury_status"] = inj_info["status"]
            player["injury_type"] = inj_info["type"]
            player["injury_timeline"] = inj_info["timeline"]
            player["injury_notes"] = inj_info["notes"]
            player["injury_impact"] = inj_info["impact_summary"]
        else:
            player["injury_status"] = "ACTIVE"
            player.pop("injury_type", None)
            player.pop("injury_timeline", None)
            player.pop("injury_notes", None)
            player.pop("injury_impact", None)

    def get_all_players(self) -> List[Dict[str, Any]]:
        """Return full player list with contextual model calculations."""
        result = []
        for p in self.players_db.values():
            item = dict(p)
            item["contextual_proj"] = self._calculate_contextual_points(item)
            item["ceiling_proj"] = round(item["contextual_proj"] * 1.35, 1)
            item["floor_proj"] = round(item["contextual_proj"] * 0.65, 1)
            item["arbitrage_delta"] = round(item["contextual_proj"] - item["espn_proj"], 1)
            result.append(item)
        return sorted(result, key=lambda x: x["adp"])

    def _calculate_contextual_points(self, player: Dict[str, Any]) -> float:
        base = player.get("xfp", player.get("projected_week", 10.0))
        implied_pts = player.get("implied_team_pts", 22.0)
        spread = player.get("spread", 0.0)
        wind = player.get("wind_mph", 0)
        is_dome = player.get("is_dome", False)
        opp_rank = player.get("opp_rank_vs_pos", 16)
        pos = player.get("position", "WR")

        vegas_factor = 1.0 + (implied_pts - 22.0) * 0.015
        matchup_factor = 1.0 + ((opp_rank - 16) / 32.0) * 0.12

        weather_penalty = 1.0
        if not is_dome and wind >= 15:
            if pos in ["QB", "WR"]:
                weather_penalty = max(0.80, 1.0 - (wind - 15) * 0.015)
            elif pos == "K":
                weather_penalty = max(0.70, 1.0 - (wind - 12) * 0.025)
            elif pos == "RB":
                weather_penalty = 1.05

        spread_factor = 1.0
        if pos == "RB" and spread <= -4.0:
            spread_factor = 1.05
        elif pos in ["WR", "QB"] and spread >= 4.0:
            spread_factor = 1.04

        # QB Goal-Line TD Vulture Penalty (e.g. PHI Tush Push, BAL Lamar runs, BUF Josh Allen sneaks)
        qb_vulture_penalty = 1.0
        team = player.get("team", "")
        if pos == "RB":
            if team == "PHI":  # Jalen Hurts Brotherly Shove / Tush Push penalty
                qb_vulture_penalty = 0.90
        # Full-PPR Target Volume Advantage (Receptions are worth 1.0 point each)
        target_share = player.get("target_share", 0.0)
        ppr_target_factor = 1.0
        if pos == "RB":
            if target_share >= 0.16:
                ppr_target_factor = 1.06  # High-leverage PPR pass-catcher
            elif target_share <= 0.12:
                ppr_target_factor = 0.95  # Low-volume receiver penalized in Full PPR

        # Injury Status Impact & Availability Risk Factor
        injury_status = str(player.get("injury_status", "ACTIVE")).upper()
        injury_factor = 1.0
        if injury_status in ["OUT", "IR", "PUP", "SUSPENDED", "CUT"]:
            injury_factor = 0.0
        elif injury_status in ["DOUBTFUL", "D"]:
            injury_factor = 0.40
        elif injury_status in ["QUESTIONABLE", "Q"]:
            inj_details = get_injury_details(player.get("name", ""), injury_status, player.get("injury_type"), player.get("injury_notes"))
            if inj_details and "discount_factor" in inj_details:
                injury_factor = inj_details["discount_factor"]
            else:
                injury_factor = 0.90

        final_proj = base * vegas_factor * matchup_factor * weather_penalty * spread_factor * qb_vulture_penalty * ppr_target_factor * injury_factor
        return round(final_proj, 1)

    def get_player(self, player_id: str) -> Optional[Dict[str, Any]]:
        p = self.players_db.get(player_id)
        if not p:
            # Check by alias or normalized name
            norm_id = str(player_id).lower().replace(".", "").replace("'", "").replace("-", " ").strip()
            for cand in self.players_db.values():
                cand_name = cand["name"].lower().replace(".", "").replace("'", "").replace("-", " ").strip()
                if cand_name == norm_id or cand_name.endswith(norm_id) or norm_id.endswith(cand_name):
                    p = cand
                    break
        if not p:
            return None
        item = dict(p)
        item["contextual_proj"] = self._calculate_contextual_points(item)
        item["ceiling_proj"] = round(item["contextual_proj"] * 1.35, 1)
        item["floor_proj"] = round(item["contextual_proj"] * 0.65, 1)
        item["arbitrage_delta"] = round(item["contextual_proj"] - item["espn_proj"], 1)
        return item

    def sync_with_live_nfl_feed(self) -> Dict[str, Any]:
        """Syncs all players directly with live official NFL transactions and rosters."""
        try:
            from backend.app.services.live_nfl_sync import fetch_live_nfl_database, sync_cut_players
            from backend.app.services.injury_records_service import sync_espn_injuries
            raw_feed = fetch_live_nfl_database()
            if not raw_feed:
                return {"status": "error", "message": "Failed to fetch live NFL feed"}

            updated_count = 0
            cuts_count = 0

            # Match by normalized name
            name_lookup = {}
            for pid, pdata in raw_feed.items():
                fname = pdata.get("full_name") or f"{pdata.get('first_name', '')} {pdata.get('last_name', '')}".strip()
                if fname and pdata.get("position") in {"QB", "RB", "WR", "TE", "K", "DEF"}:
                    norm_name = fname.lower().replace(".", "").replace("'", "").replace("-", " ")
                    name_lookup[norm_name] = pdata

            # Detect and update cut players
            cut_sync_result = sync_cut_players(self.players_db, raw_feed)
            cuts_count = cut_sync_result.get("cuts_updated", 0)

            for player in self.players_db.values():
                norm = player["name"].lower().replace(".", "").replace("'", "").replace("-", " ")
                live_match = name_lookup.get(norm)
                if live_match:
                    live_team = live_match.get("team")
                    # Update team changes and handle cuts
                    if live_team is None:
                        # Player is cut/waived
                        if player.get("team"):
                            player["team"] = None
                            player["injury_status"] = "CUT"
                            player["depth_chart_order"] = 99
                            cuts_count += 1
                            logger.info(f"Detected cut: {player['name']} (was {player.get('team')})")
                    elif player.get("team") != live_team:
                        # Player was traded to different team
                        player["team"] = live_team
                        updated_count += 1

                    live_injury = live_match.get("injury_status")
                    current_status = player.get("injury_status", "").upper()
                    # Preserve administrative statuses (SUSPENDED) that were manually set
                    if live_injury and live_injury.upper() != "CUT" and current_status not in ["SUSPENDED", "CUT"]:
                        player["injury_status"] = live_injury.upper()

                    if live_match.get("depth_chart_order"):
                        player["depth_chart_order"] = live_match.get("depth_chart_order")

            # Sync ESPN injury data to both players_db and injury_records table
            espn_injury_updates = 0
            try:
                from backend.app.services.espn_service import espn_service
                if espn_service.is_connected and espn_service.espn_league_instance:
                    # Build league data for injury_records_service
                    league_data = {"teams": []}
                    for team in espn_service.espn_league_instance.teams:
                        team_data = {
                            "roster": []
                        }
                        for player_obj in getattr(team, 'roster', []):
                            player_name = getattr(player_obj, 'name', '')
                            player_injury = getattr(player_obj, 'injuryStatus', None) or "ACTIVE"
                            player_id = getattr(player_obj, 'playerId', getattr(player_obj, 'player_id', ''))
                            injury_info = getattr(player_obj, 'injury', {})
                            body_part = getattr(injury_info, 'displayName', None) if injury_info else None

                            team_data["roster"].append({
                                "player": {
                                    "id": player_id,
                                    "fullName": player_name,
                                    "injuryStatus": player_injury,
                                    "injury": {
                                        "displayName": body_part,
                                        "detail": None
                                    }
                                }
                            })

                            # Find matching player in our players_db and update
                            norm_espn_name = player_name.lower().replace(".", "").replace("'", "").replace("-", " ")
                            for player in self.players_db.values():
                                norm_db_name = player["name"].lower().replace(".", "").replace("'", "").replace("-", " ")
                                if norm_db_name == norm_espn_name:
                                    current_status = player.get("injury_status", "").upper()
                                    # Update injury status from ESPN, but preserve CUT and SUSPENDED
                                    if player_injury and player_injury.upper() != "CUT" and current_status not in ["CUT", "SUSPENDED"]:
                                        if player.get("injury_status") != player_injury:
                                            player["injury_status"] = player_injury.upper()
                                            espn_injury_updates += 1
                                    break

                        league_data["teams"].append(team_data)

                    # Sync to injury_records table
                    injury_sync_result = sync_espn_injuries(league_data)
                    logger.info(f"Injury records synced: {injury_sync_result.get('espn_injury_synced', 0)} records updated")

            except Exception as e:
                logger.warning(f"ESPN injury sync failed: {e}")

            logger.info(f"Live NFL sync complete: {updated_count} trades, {cuts_count} cuts, {espn_injury_updates} ESPN injury updates, {len(self.players_db)} total verified.")
            return {
                "status": "success",
                "trades_updated": updated_count,
                "cuts_detected": cuts_count,
                "espn_injury_updates": espn_injury_updates,
                "total_verified": len(self.players_db)
            }
        except Exception as e:
            logger.error(f"Live sync error: {e}")
            return {"status": "error", "message": str(e)}

    def refresh_players(self) -> Dict[str, Any]:
        """Refresh player data from live sources"""
        return self.sync_with_live_nfl_feed()

nfl_stats_service = NFLStatsService()
